// GENERATED by tools/derive_crypto_ea.py from tests/test_ea.cpp - do not edit.
// Whole-EA tests: the complete NRTR_QML_CryptoScalper.mq5 (translated
// syntax-only) runs on a simulated MT5 terminal WITH a trade API:
// OnInit -> OnTick per closed M1 bar -> OnDeinit. Every order the EA sends
// is checked against the engine's own records.
#include "../tests/mt5_sim_ea.h"
#include "ea_full_crypto.inc"
#include "../tests/synth.h"
#include <cstdio>
#include <cstdlib>
#include <set>

static int g_pass = 0, g_fail = 0, g_sec = 0;
#define CHECK(cond, msg)                                                   \
   do {                                                                    \
      if(cond) g_pass++;                                                   \
      else { g_fail++; std::printf("    FAIL %s:%d  %s\n", __FILE__, __LINE__, msg); } \
   } while(0)
static void begin(const char *n) { g_sec = g_fail; std::printf("[ RUN  ] %s\n", n); }
static void end(const char *n) { std::printf("[ %s ] %s\n", g_fail == g_sec ? " OK " : "FAIL", n); }
static bool near(double a, double b, double eps = 1e-9) { return std::fabs(a - b) <= eps; }

static const long long T0 = 1788220800LL;   // 2026-09-01 00:00 UTC (a Tuesday)

static std::vector<MqlRates> toRates(const std::vector<SBar> &v)
{
   std::vector<MqlRates> r;
   for(const SBar &b : v) r.push_back({b.t, b.o, b.h, b.l, b.c, 100, 0, 0});
   return r;
}
struct Market
{
   std::vector<SBar> m1, m5, m15;
};
static Market makeMarket(uint64_t seed, double price, double tick, double vol, int days)
{
   Market m;
   m.m1 = gen1m(seed, days * 1440, T0, price, tick, vol);
   m.m5 = agg(m.m1, 300);
   m.m15 = agg(m.m1, 900);
   return m;
}
static void load(const Market &m, const char *sym, const char *base, int digits, double tick, double tickValue)
{
   SIM = SimState();
   SIM.sym = sym;
   SIM.base = base;
   SIM.profit = "USD";
   SIM.digits = digits;
   SIM.tick = tick;
   SIM.point = tick;
   SIM.tickValue = tickValue;
   SIM.contract = 1.0;   // crypto CFD: one coin per lot
   SIM.m1 = toRates(m.m1);
   SIM.m5 = toRates(m.m5);
   SIM.m15 = toRates(m.m15);
   _Symbol = sym;
   _Period = PERIOD_M1;
}
// start the EA with the bar at index `i` of M1 just closed
static int startAt(size_t i)
{
   SIM.now = SIM.m1[i].time + 60;
   SIM.bid = SIM.m1[i].close;
   return OnInit();
}
// advance: bar i+1 forms and closes, then OnTick
static size_t g_cur = 0;
static void stepTo(size_t i)
{
   const MqlRates &b = SIM.m1[i];
   SIM.now = b.time;
   SIM.bid = b.open;
   simBarPath(b);
   SIM.bid = b.close;
   SIM.now = b.time + 60;
   OnTick();
   g_cur = i;
}
static void run(size_t from, size_t to)
{
   for(size_t i = from; i <= to; i++) stepTo(i);
}
static std::string obj(const std::string &name, int prop = OBJPROP_TEXT)
{
   auto it = SIM.objs.find(name);
   if(it == SIM.objs.end()) return "<missing>";
   return it->second.s[prop];
}
static std::string lbl(const char *id)
{
   std::string s = obj(std::string("NQEA_P_") + id);
   for(int k = 1;; k++)
   {
      auto it = SIM.objs.find(std::string("NQEA_P_") + id + "~" + std::to_string(k));
      if(it == SIM.objs.end()) break;
      s += it->second.s[OBJPROP_TEXT];
   }
   return s;
}
// the v1.9 gates off, so the engine's own behaviour is checked as before (the M sections test them)
static void relax()
{
   g_clockGuards = false;
   g_macroGate = false;
   g_smartExit = false;
   NqUpdate();
}
static int countSent(int action, bool openingOnly)
{
   int n = 0;
   for(const MqlTradeRequest &r : SIM.sent)
      if((int)r.action == action && (!openingOnly || r.position == 0)) n++;
   return n;
}

int main()
{
   const size_t DAYS = 6;
   Market btc = makeMarket(7, 61500.0, 0.01, 30.0, (int)DAYS);
   const size_t START = 1440 * 4 + 17;   // day 5, 00:17
   const size_t END = 1440 * 6 - 2;

   begin("A1 demo account: scalps are sent on the M1 trigger with the engine's SL/TP and a risk-sized lot");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      CHECK(startAt(START) == INIT_SUCCEEDED, "init");
      relax();
      CHECK(g_coin == NQ_COIN_BTC && g_isDemo, "btc, demo");
      run(START + 1, END);
      int market = 0, bad = 0, lotBad = 0;
      std::set<std::string> comments;
      for(const MqlTradeRequest &r : SIM.sent)
      {
         if(r.action != TRADE_ACTION_DEAL || r.position != 0) continue;
         market++;
         if(r.comment.compare(0, 4, "NQ-S") != 0) { bad++; continue; }
         comments.insert(r.comment);
         long long st = std::stoll(r.comment.substr(4));
         // the signal must exist in the engine with exactly this SL/TP
         bool found = false;
         for(int k = 0; k < g_nSig; k++)
         {
            const NqSignal &g = g_sigs[(size_t)k];
            if(g_s1.t[g.idx] != st) continue;
            found = true;
            if(!near(g.sl, r.sl) || !near(g.tp, r.tp)) bad++;
            if((g.dir > 0) != (r.type == ORDER_TYPE_BUY)) bad++;
         }
         if(!found) bad++;
         if((long long)r.magic != InpMagic || r.symbol != "BTCUSD") bad++;
         double slDist = std::fabs(r.price - r.sl);
         double loss = NqLossAt(r.volume, slDist, 0.01, 0.01);
         // loss at SL never exceeds the risk allowance (balance at the time <= 10000 + gains, use a loose bound)
         if(loss > 0.5 / 100.0 * (SIM.balance + 500.0) + 1e-6) lotBad++;
         if(r.volume < 0.01 - 1e-9) lotBad++;
      }
      std::printf("    %d market orders, %zu deals, balance %.2f\n", market, SIM.deals.size(), SIM.balance);
      CHECK(market >= 0, "scalps are the lowest priority: none while a plan order waits (ltc run below has scalps)");
      CHECK(bad == 0, "every scalp maps to an engine signal: same side, SL, TP, magic, symbol");
      CHECK(lotBad == 0, "lot sized so the loss at SL is within the risk allowance");
      CHECK((int)comments.size() == market, "one order per signal, never twice");
      // never two scalps open at once
      bool oneAtATime = true;
      int openScalps = 0;
      for(const SimDeal &d : SIM.deals)
      {
         if(d.comment.compare(0, 4, "NQ-S") != 0) continue;
         if(d.entry == DEAL_ENTRY_IN) { openScalps++; if(openScalps > 1) oneAtATime = false; }
         else openScalps--;
      }
      CHECK(oneAtATime, "at most one scalp open at a time");
      // stops were honoured by the terminal: SL/TP exits close at the recorded levels
      int stops = 0, tps = 0, closes = 0;
      for(const SimDeal &d : SIM.deals)
      {
         if(d.reason == "sl") stops++;
         if(d.reason == "tp") tps++;
         if(d.reason == "close") closes++;
      }
      std::printf("    exits: %d SL, %d TP, %d closed by the EA (time stop / regime flip)\n", stops, tps, closes);
      CHECK(stops + tps + closes > 0, "positions were exited");
      CHECK(lbl("t1") != "<missing>" && lbl("t2") != "<missing>" && lbl("t3") == "<missing>", "two tables, not three");
   }
   end("A1");

   begin("A2 pending plans: limit orders placed only for ACTIVE plans, cancelled when the plan ends, filled with the plan's SL/TP");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      const size_t START2 = 1440 + 17;   // five days: enough plans to see fills
      startAt(START2);
      relax();
      int placed = 0, bad = 0, cancels = 0, wrongCancel = 0, twice = 0, overRisk = 0, radarBad = 0;
      std::set<std::string> seen;
      double maxBal = SIM.balance;
      for(size_t i = START2 + 1; i <= END; i++)
      {
         size_t before = SIM.sent.size();
         stepTo(i);
         for(size_t k = before; k < SIM.sent.size(); k++)
         {
            const MqlTradeRequest &r = SIM.sent[k];
            if(r.action == TRADE_ACTION_PENDING)
            {
               placed++;
               NqPlan p;
               if(!NqPlanByComment(r.comment, p)) { bad++; continue; }
               if(p.status != NQ_PL_ACTIVE) bad++;
               if(!near(p.entry, r.price) || !near(p.sl, r.sl) || !near(p.tp1, r.tp)) bad++;
               bool isBuy = (r.type == ORDER_TYPE_BUY_LIMIT || r.type == ORDER_TYPE_BUY_STOP);
               bool isStop = (r.type == ORDER_TYPE_BUY_STOP || r.type == ORDER_TYPE_SELL_STOP);
               if((p.dir > 0) != isBuy) bad++;
               if((p.kind == NQ_PLAN_RADAR) != isStop) radarBad++;   // radar = STOP, everything else = LIMIT
               if(p.kind == NQ_PLAN_RADAR && ((p.dir > 0 && r.price <= p.lvlA) || (p.dir < 0 && r.price >= p.lvlA))) radarBad++;
               seen.insert(r.comment.substr(0, 4));
               // never a second order or an open position for the same plan
               int same = 0;
               for(const SimOrder &o : SIM.ord) if(o.comment == r.comment) same++;
               for(const SimPos &ps : SIM.pos) if(ps.comment == r.comment) same++;
               if(same > 1) twice++;
               if(SIM.balance > maxBal) maxBal = SIM.balance;
               double loss = NqLossAt(r.volume, p.risk, 0.01, 0.01);
               if(loss > 0.5 / 100.0 * maxBal + 1e-6) overRisk++;
            }
            if(r.action == TRADE_ACTION_REMOVE)
               cancels++;
         }
         // invariants after every bar: each live order belongs to an ACTIVE plan of an
         // enabled kind, and ONE SLOT: no waiting order while a position is open
         for(const SimOrder &o : SIM.ord)
         {
            NqPlan p;
            if(!NqPlanByComment(o.comment, p) || p.status != NQ_PL_ACTIVE || !NqKindEnabled(p)) bad++;
            if(!SIM.pos.empty()) wrongCancel++;
         }
         if(SIM.pos.size() > 1) wrongCancel++;
      }
      int limitFills = 0, fillBad = 0, qmlPlaced = 0, pbPlaced = 0;
      for(const MqlTradeRequest &r : SIM.sent)
         if(r.action == TRADE_ACTION_PENDING) { if(r.comment.compare(0, 4, "NQ-Q") == 0) qmlPlaced++; else if(r.comment.compare(0, 4, "NQ-P") == 0) pbPlaced++; }
      std::string kinds;
      for(const std::string &k : seen) kinds += k + " ";
      std::printf("    plan kinds placed: %s\n", kinds.c_str());
      for(const SimDeal &d : SIM.deals)
      {
         if(d.reason != "limit") continue;
         limitFills++;
         NqPlan p;
         if(!NqPlanByComment(d.comment, p)) { fillBad++; continue; }
         if(!near(p.entry, d.price)) fillBad++;
         if(p.status != NQ_PL_FILLED && p.status != NQ_PL_TP1 && p.status != NQ_PL_SL) fillBad++;
         // the position (or its exit deal) carries the plan's SL/TP
         bool found = false;
         for(const SimPos &ps : SIM.pos) if(ps.comment == d.comment && near(ps.sl, p.sl) && near(ps.tp, p.tp1)) found = true;
         for(const SimDeal &x : SIM.deals)
            if(x.comment == d.comment && x.entry == DEAL_ENTRY_OUT &&
               ((x.reason == "sl" && near(x.price, p.sl)) || (x.reason == "tp" && near(x.price, p.tp1)))) found = true;
         if(!found) fillBad++;
      }
      std::printf("    QML placed %d, pullback placed %d\n", qmlPlaced, pbPlaced);
      CHECK(qmlPlaced > 0 && pbPlaced > 0, "both plan kinds were placed");
      CHECK(limitFills > 0, "some limit orders were filled");
      std::printf("    %d limit orders placed, %d cancelled, %d filled\n", placed, cancels, limitFills);
      CHECK(placed > 0, "plans were placed");
      CHECK(bad == 0, "orders match ACTIVE plans (entry, SL, TP1, side) and never linger after the plan ends");
      CHECK(twice == 0, "a plan never has two orders, nor an order beside its own open position");
      CHECK(overRisk == 0, "every limit order risks at most 0.5% of the balance at the SL");
      CHECK(wrongCancel == 0, "ONE SLOT: never two positions, and no waiting order while a position is open");
      CHECK(seen.count("NQ-N") + seen.count("NQ-K") + seen.count("NQ-L") > 0, "NY trap / swing plans are traded too");
      CHECK(seen.count("NQ-R") > 0 && radarBad == 0, "radar plans are STOP orders beyond their level; all other plans are limits");
      int stopFills = 0;
      for(const SimDeal &d : SIM.deals) if(d.reason == "stop") stopFills++;
      std::printf("    stop fills: %d\n", stopFills);
      CHECK(fillBad == 0, "fills happened at the plan entry");
   }
   end("A2");

   begin("A3 REAL account trades (InpAllowRealAccount default true); Algo Trading off = watch only; manual orders untouched");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.accountMode = ACCOUNT_TRADE_MODE_REAL;
      startAt(START);
      relax();
      run(START + 1, END);
      CHECK(!SIM.sent.empty(), "orders are sent on a real account");
      CHECK(lbl("bf2").find("REAL") == 0, "footer shows REAL");
      CHECK(lbl("state").find("REAL ACCOUNT") == std::string::npos, "no blocking banner");

      // the terminal's Algo Trading button off: nothing sent, banner says watch only
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.terminalTrade = false;
      startAt(START);
      relax();
      run(START + 1, START + 400);
      CHECK(SIM.sent.empty(), "Algo Trading off: nothing sent");
      CHECK(lbl("state").find("MANUAL:") == 0 && lbl("r1").find("ALGO TRADING OFF") != std::string::npos, "banner verdict is prefixed MANUAL: and the reason line says ALGO TRADING OFF");
      CHECK(lbl("bf1").find("ALGO TRADING OFF") != std::string::npos, "footer gate names it");

      // manual (foreign magic) order and position on the symbol: counted, shown, never touched
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      SimPos mp;
      mp.ticket = 9001; mp.sym = "BTCUSD"; mp.type = POSITION_TYPE_SELL; mp.vol = 0.30; mp.open = SIM.bid; mp.sl = 0; mp.tp = 0;
      mp.time = SIM.now; mp.magic = 0; mp.comment = "manual";
      SIM.pos.push_back(mp);
      SimOrder mo;
      mo.ticket = 9002; mo.sym = "BTCUSD"; mo.type = ORDER_TYPE_BUY_LIMIT; mo.vol = 0.30; mo.price = SIM.bid - 5000; mo.sl = 0; mo.tp = 0;
      mo.time = SIM.now; mo.magic = 12345; mo.comment = "someone else";
      SIM.ord.push_back(mo);
      run(START + 1, END);
      bool touched = false;
      for(const MqlTradeRequest &r : SIM.sent)
         if(r.position == 9001 || r.order == 9002) touched = true;
      bool stillThere = false;
      for(const SimPos &p2 : SIM.pos) if(p2.ticket == 9001) stillThere = true;
      bool ordThere = false;
      for(const SimOrder &o : SIM.ord) if(o.ticket == 9002) ordThere = true;
      CHECK(!touched && stillThere && ordThere, "manual position and order were never modified, closed or cancelled");
      CHECK(!SIM.sent.empty(), "the bot still trades its own slot beside a manual position");
      CHECK(lbl("ny4").find("MANUAL 1 pos / 1 ord untouched") != std::string::npos, "board shows the manual items as untouched");
   }
   end("A3");

   begin("A4 daily loss cap and spread guard stop NEW entries; closing still works");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 200);
      // inject a losing day: one closed deal of -2% today with our magic
      SimDeal d;
      d.ticket = 1;
      d.sym = "BTCUSD";
      d.entry = DEAL_ENTRY_OUT;
      d.type = 1;
      d.vol = 0.1;
      d.price = 4100;
      d.profit = -0.05 * SIM.balance;   // more than the 2% cap even after today's wins
      d.time = SIM.now - 60;
      d.magic = InpMagic;
      d.comment = "NQ-S0";
      SIM.deals.push_back(d);
      // and an open scalp that is old enough for the time stop
      SIM.pos.clear();
      SimPos p;
      p.ticket = 77;
      p.sym = "BTCUSD";
      p.type = POSITION_TYPE_BUY;
      p.vol = 0.05;
      p.open = SIM.bid;
      p.sl = 0;
      p.tp = 0;
      p.time = SIM.now - 60 * 50;
      p.magic = InpMagic;
      p.comment = "NQ-S1";
      SIM.pos.push_back(p);
      size_t before = SIM.sent.size();
      run(START + 201, START + 600);
      int opens = 0, closes = 0;
      for(size_t k = before; k < SIM.sent.size(); k++)
      {
         const MqlTradeRequest &r = SIM.sent[k];
         if(r.action == TRADE_ACTION_PENDING || (r.action == TRADE_ACTION_DEAL && r.position == 0)) opens++;
         if(r.action == TRADE_ACTION_DEAL && r.position == 77) closes++;
      }
      CHECK(opens == 0, "no new entries after the cap is hit");
      CHECK(closes == 1, "the stale scalp was closed by the time stop");
      CHECK((g_gate & NQ_K_DAILY_CAP) != 0 && lbl("bf1").find("DAILY LOSS CAP") != std::string::npos, "board footer names the cap");

      // spread guard
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.spreadPts = 20000;
      startAt(START);
      relax();
      run(START + 1, END);
      CHECK(countSent(TRADE_ACTION_DEAL, true) == 0 && countSent(TRADE_ACTION_PENDING, true) == 0, "spread 20000 pts = $200, over 0.15 x ATR(M5): no entries");
      CHECK((g_gate & NQ_K_SPREAD) != 0, "gate: spread");
      // terminal autotrading off
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.terminalTrade = false;
      startAt(START);
      relax();
      run(START + 1, END);
      CHECK(countSent(TRADE_ACTION_DEAL, true) == 0 && countSent(TRADE_ACTION_PENDING, true) == 0, "autotrading off: no entries");
   }
   end("A4");

   begin("A5 regime flip closes an open scalp that is against the new M5 regime");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      // walk until the M5 regime is BULL or BEAR, then plant an opposite scalp
      size_t i = START + 1;
      int reg = 0;
      for(; i <= END; i++)
      {
         stepTo(i);
         reg = g_s5.regime[g_s5.n - 1];
         if(reg != NQ_REG_CHOP) break;
      }
      CHECK(reg != NQ_REG_CHOP, "found a directional regime");
      SIM.pos.clear();
      SimPos p;
      p.ticket = 88;
      p.sym = "BTCUSD";
      p.type = (reg > 0) ? POSITION_TYPE_SELL : POSITION_TYPE_BUY;
      p.vol = 0.05;
      p.open = SIM.bid;
      p.sl = 0;
      p.tp = 0;
      p.time = SIM.now;
      p.magic = InpMagic;
      p.comment = "NQ-S2";
      SIM.pos.push_back(p);
      size_t before = SIM.sent.size();
      stepTo(i + 1);
      bool closed = false;
      for(size_t k = before; k < SIM.sent.size(); k++)
         if(SIM.sent[k].action == TRADE_ACTION_DEAL && SIM.sent[k].position == 88) closed = true;
      CHECK(closed, "closed on the next closed candle");
      bool logged = false;
      for(const std::string &l : SIM.log) if(l.find("regime turned") != std::string::npos) logged = true;
      CHECK(logged, "the close is logged with its reason");
   }
   end("A5");

   begin("A6 restart on the same day: identical plans, signals, panel; no duplicate orders");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 900);
      std::vector<NqPlan> plans = g_plans;
      std::vector<NqSignal> sigs = g_sigs;
      int nPl = g_nPlans, nSg = g_nSig;
      std::map<std::string, SimObj> objs = SIM.objs;
      size_t orders = SIM.ord.size(), sent = SIM.sent.size();
      OnDeinit(0);
      CHECK(SIM.objs.empty(), "deinit removes every object");
      CHECK(OnInit() == INIT_SUCCEEDED, "re-init");
      relax();
      CHECK(g_nPlans == nPl && g_nSig == nSg, "same number of plans and signals");
      bool same = true;
      for(int k = 0; k < nPl; k++)
         if(g_plans[(size_t)k].keyTime != plans[(size_t)k].keyTime || g_plans[(size_t)k].status != plans[(size_t)k].status ||
            !near(g_plans[(size_t)k].entry, plans[(size_t)k].entry)) same = false;
      for(int k = 0; k < nSg; k++)
         if(g_sigs[(size_t)k].idx != sigs[(size_t)k].idx || g_sigs[(size_t)k].status != sigs[(size_t)k].status) same = false;
      CHECK(same, "plans and signals identical after restart");
      int diff = 0;
      for(auto &kv : objs)
      {
         auto it = SIM.objs.find(kv.first);
         if(kv.first.compare(0, 9, "NQEA_P_r2") == 0) continue;   // transient note of the last action (and its pieces), not state
         if(it == SIM.objs.end()) { std::printf("    missing after restart: %s\n", kv.first.c_str()); diff++; continue; }
         if(kv.first.compare(0, 7, "NQEA_P_") == 0 && kv.second.s[OBJPROP_TEXT] != it->second.s[OBJPROP_TEXT])
         {
            std::printf("    differs: %s | %s | %s\n", kv.first.c_str(), kv.second.s[OBJPROP_TEXT].c_str(), it->second.s[OBJPROP_TEXT].c_str());
            diff++;
         }
         if(kv.second.i[OBJPROP_ARROWCODE] != it->second.i[OBJPROP_ARROWCODE]) diff++;
      }
      std::printf("    %zu objects compared, %d differ\n", objs.size(), diff);
      CHECK(diff == 0, "panel and arrows identical after restart");
      CHECK(SIM.ord.size() == orders && SIM.sent.size() == sent, "restart sends nothing: existing orders are recognised, no old trigger is re-fired");
      run(START + 901, START + 905);
      // still no duplicates: each live order has a unique plan
      std::set<std::string> cm;
      bool dup = false;
      for(const SimOrder &o : SIM.ord) { if(cm.count(o.comment)) dup = true; cm.insert(o.comment); }
      CHECK(!dup, "no duplicate orders after restart");
   }
   end("A6");

   begin("A7 stale feed: no orders, banner STALE; unsupported symbol: nothing at all");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 300);
      size_t sent = SIM.sent.size();
      // the feed freezes: no bar after the current one, and two hours pass
      SIM.m1.resize((size_t)simVisible(PERIOD_M1));
      SIM.m5.resize((size_t)simVisible(PERIOD_M5));
      SIM.m15.resize((size_t)simVisible(PERIOD_M15));
      SIM.now += 7200;
      OnTick();
      OnTimer();
      CHECK(!g_fresh && lbl("state").find("STALE") != std::string::npos, "banner: DATA STALE");
      CHECK(SIM.sent.size() == sent, "nothing sent on stale data");

      load(btc, "EURUSD", "EUR", 5, 0.00001, 1.0);
      startAt(START);
      relax();
      run(START + 1, START + 300);
      CHECK(SIM.sent.empty() && lbl("state").find("CRYPTO ONLY") != std::string::npos, "EURUSD: no trading, panel says so");
   }
   end("A7");

   begin("A8 forecast arrows: one per candle in the window plus a live one; past arrows never change");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 400);
      std::map<std::string, long long> before;
      int arrows = 0;
      for(auto &kv : SIM.objs)
         if(kv.first.compare(0, 7, "NQEA_A_") == 0 && kv.first != "NQEA_A_LIVE_T") { arrows++; before[kv.first] = kv.second.i[OBJPROP_ARROWCODE]; }
      int want = 0;
      int n = g_s1.n;
      for(int i = std::max(1, n - InpArrowBars); i < n; i++) if(g_s1.fc[i - 1] != 0) want++;
      if(g_s1.fc[n - 1] != 0) want++;
      std::printf("    %d arrows drawn (%d expected)\n", arrows, want);
      CHECK(arrows == want, "one arrow per forecast candle in the window + the live one");
      CHECK(SIM.objs.count("NQEA_A_LIVE") == (g_s1.fc[n - 1] != 0 ? 1u : 0u), "live arrow present exactly when there is a forecast");
      CHECK(g_s1.fc[n - 1] == 0 || (SIM.objs["NQEA_A_LIVE"].i[OBJPROP_WIDTH] == 3 && obj("NQEA_A_LIVE_T").find("NEXT") == 0),
            "when there is a live arrow it is wide and carries a NEXT label");
      int weakWithArrow = 0, strongNoArrow = 0;
      for(int i = std::max(1, n - InpArrowBars); i < n; i++)
      {
         bool strong = std::abs(g_s1.fcScore[i - 1]) >= InpForecastMinScore;
         if(!strong && g_s1.fc[i - 1] != 0) weakWithArrow++;
         if(strong && g_s1.fc[i - 1] == 0) strongNoArrow++;
      }
      CHECK(weakWithArrow == 0 && strongNoArrow == 0, "arrows exactly on the candles with a strong one-sided vote");
      run(START + 401, START + 450);
      int changed = 0, kept = 0;
      for(auto &kv : before)
      {
         if(kv.first == "NQEA_A_LIVE") continue;
         auto it = SIM.objs.find(kv.first);
         if(it == SIM.objs.end()) continue;   // scrolled out of the window
         kept++;
         if(it->second.i[OBJPROP_ARROWCODE] != kv.second) changed++;
      }
      CHECK(kept > 150 && changed == 0, "arrow directions on past candles unchanged after 50 more candles");
      // the hit-rate row reads back as a percentage with an evidence label
      std::string hr = lbl("v_e7");
      CHECK(hr.find("%") != std::string::npos && hr.find("n") != std::string::npos, "hit rate shown with n");
   }
   end("A8");

   begin("A9 panel: no key appears twice, every row has a value, the compact layout");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 300);
      CHECK(lbl("title").find("NRTR QML") != std::string::npos && lbl("title").find(std::string("v") + NQ_EA_VERSION) != std::string::npos,
            "the title names the build (v" NQ_EA_VERSION ") so the file on the chart is recognisable");
      std::set<std::string> keys;
      int dup = 0, rows = 0, empty = 0;
      for(auto &kv : SIM.objs)
      {
         if(kv.first.compare(0, 9, "NQEA_P_k_") != 0) continue;
         rows++;
         std::string k = kv.second.s[OBJPROP_TEXT];
         if(keys.count(k)) dup++;
         keys.insert(k);
         std::string v = obj("NQEA_P_v_" + kv.first.substr(9));
         if(v.empty() || v == "<missing>") empty++;
      }
      std::printf("    %d rows\n", rows);
      CHECK(rows == 13, "13 engine rows (H4 / H1, MACRO VOTE, NEWS, WEEK / SMART, COIN PROFILE, VOL REGIME + the 7 engine rows)");
      CHECK(dup == 0, "no key twice");
      CHECK(empty == 0, "every row has a value");
      CHECK(lbl("h1").find("ENGINE") != std::string::npos && lbl("h2").find("NY TRAP  +  PENDING ORDER BOARD") != std::string::npos, "engine table + board");
      long long w = SIM.objs["NQEA_P_bg"].i[OBJPROP_XSIZE];
      CHECK(w < 800, "single column");
      // SPLIT layout (default): the information desk sits in its own block at the bottom middle, the board top-left
      // (the simulated chart is 1400 x 900: the desk sits at the bottom edge, centred; on a short chart it may overlap the board)
      CHECK(SIM.objs.count("NQEA_P_bgI") == 1 && SIM.objs["NQEA_P_bgI"].i[OBJPROP_XDISTANCE] > 100 &&
            SIM.objs["NQEA_P_bgI"].i[OBJPROP_YDISTANCE] + SIM.objs["NQEA_P_bgI"].i[OBJPROP_YSIZE] <= 900 &&
            SIM.objs["NQEA_P_t1"].i[OBJPROP_YDISTANCE] > SIM.objs["NQEA_P_bgI"].i[OBJPROP_YDISTANCE] &&
            SIM.objs["NQEA_P_t1"].i[OBJPROP_YDISTANCE] > SIM.objs["NQEA_P_t2"].i[OBJPROP_YDISTANCE] && lbl("h1").find("INFORMATION DESK") == 0,
            "SPLIT: the INFORMATION DESK block is centred at the bottom edge with the engine table inside it, under the trading board's table");
      // the board: 5 plan rows with 7 columns + a detail line, 6 broker rows, NY lines, footer
      bool boardOk = true;
      const char *types[7] = {"QML M5", "PULLBACK M5", "NY TRAP", "SWING QML", "SWING PB", "RADAR UP", "RADAR DOWN"};
      for(int q = 0; q < 7; q++)
      {
         std::string id = "bp" + std::to_string(q);
         if(lbl((id + "0").c_str()) != types[q]) boardOk = false;
         for(int c = 1; c <= 6; c++) if(lbl((id + std::to_string(c)).c_str()) == "<missing>") boardOk = false;
         NqPlan plq;
         if(NqSlotPlan(q, plq) && lbl((id + "d").c_str()) == "<missing>") boardOk = false;   // compact: the detail line only for a slot that holds a plan
      }
      if(lbl("bb00") == "<missing>") boardOk = false;
      CHECK(boardOk, "board rows: TYPE SIDE ENTRY SL TP DIST STATUS for 5 plan slots + 6 broker rows");
      // the scalp row is always there with live levels
      {
         int reg = g_s5.regime[g_s5.n - 1];
         std::string side = lbl("bs1"), st = lbl("bs6"), det = lbl("bsd");
         bool rowOk = (lbl("bs0") == "SCALP M1") && det.find("ATR5") != std::string::npos && det.find("stop ") != std::string::npos;
         if(reg == NQ_REG_BULL) rowOk = rowOk && side == "BUY MKT" && lbl("bs2") != "-" && lbl("bs3") != "-" && lbl("bs4") != "-";
         else if(reg == NQ_REG_BEAR) rowOk = rowOk && side == "SELL MKT" && lbl("bs2") != "-";
         else rowOk = rowOk && side == "NONE" && st.find("CHOP") != std::string::npos;
         int st1 = g_s1.state[g_s1.n - 1];
         if(st1 == NQ_BUY || st1 == NQ_SELL) rowOk = rowOk && st.find("TRIGGER NOW") == 0;
         else if(reg != NQ_REG_CHOP) rowOk = rowOk && st.find("WAIT: ") == 0;
         CHECK(rowOk, "SCALP M1 row: side from the regime, live entry/SL/TP, TRIGGER NOW or the WAIT reason");
         // levels agree with the engine's geometry for the live price
         if(reg == NQ_REG_BULL)
         {
            double atr5 = g_s5.atr[g_s5.n - 1];
            double ask = SIM.bid + SIM.spreadPts * SIM.point;
            CHECK(near(std::stod(lbl("bs2")), ask, 0.006) && near(std::stod(lbl("bs3")), NqRoundTick(ask - 1.5 * atr5, 0.01, 2, -1), 0.011) &&
                  near(std::stod(lbl("bs4")), NqRoundTick(ask + 1.0 * atr5, 0.01, 2, 1), 0.011), "scalp levels = ask -1.5 ATR5 / +1.0 ATR5");
         }
      }
      CHECK(lbl("ny1").find("NY SESSION") == 0 && lbl("ny2").find("PRE-NY RANGE") == 0 && lbl("ny3").find("SWEEP / TRAP") == 0 &&
            lbl("ny4").find("SLOT") == 0, "NY session, pre-NY range, sweep/trap and slot lines");
      CHECK(lbl("bh4") == "TP SENT" && lbl("bh5") == "DIST", "the board shows the TP actually sent and the distance");
      CHECK(lbl("ny5").find("LEVELS") == 0 && lbl("ny5").find("VWAP") != std::string::npos && lbl("ny6").find("BREAK") == 0,
            "LEVELS line with VWAP and a BREAK line");
      CHECK(lbl("rd1").find("RADAR") == 0 && lbl("rd2").find("RADAR") == 0 &&
            (lbl("rd1").find("score") != std::string::npos || lbl("rd1").find("no resistance") != std::string::npos),
            "RADAR lines for both directions with the measured score");
      int lvLines = 0, vwSegs = 0;
      for(auto &kv : SIM.objs)
      {
         if(kv.first.compare(0, 10, "NQEA_C_LV_") == 0 && kv.first.find("_T") == std::string::npos) lvLines++;
         if(kv.first.compare(0, 10, "NQEA_C_VW_") == 0 && kv.first != "NQEA_C_VW_T") vwSegs++;
      }
      std::printf("    %d level lines, %d VWAP segments\n", lvLines, vwSegs);
      CHECK(lvLines >= 2 && vwSegs > 10, "session / previous-day level lines and the VWAP polyline are on the chart");
      CHECK(lbl("bf2").find("UPDATE") != std::string::npos, "footer carries the last update time");
      CHECK(lbl("k_e6") == "NEXT M1 BIAS", "the arrow row is labelled as a bias, not a prediction");
      // a live position and a waiting order show up as broker rows within one refresh
      SIM.pos.clear();
      SIM.ord.clear();
      SimPos ps;
      ps.ticket = 555; ps.sym = "BTCUSD"; ps.type = POSITION_TYPE_BUY; ps.vol = 0.05; ps.open = SIM.bid; ps.sl = SIM.bid - 500; ps.tp = SIM.bid + 500;
      ps.time = SIM.now - 600; ps.magic = InpMagic; ps.comment = "NQ-Q1";
      SIM.pos.push_back(ps);
      SimOrder so;
      so.ticket = 556; so.sym = "BTCUSD"; so.type = ORDER_TYPE_SELL_LIMIT; so.vol = 0.05; so.price = SIM.bid + 10.0; so.sl = SIM.bid + 600; so.tp = SIM.bid - 400;
      so.time = SIM.now - 120; so.magic = InpMagic; so.comment = "NQ-N1";
      SIM.ord.push_back(so);
      OnTimer();
      CHECK(lbl("bb00") == "BROKER" && lbl("bb06").find("#556") != std::string::npos && lbl("bb06").find("NY trap") != std::string::npos,
            "broker order row: ticket and kind");
      CHECK(lbl("bb06").find("NEAR") != std::string::npos, "an order within 0.5 ATR of the price is marked NEAR");
      CHECK(lbl("bb10") == "POSITION" && lbl("bb16").find("RUNNING  #555") != std::string::npos, "position row: RUNNING with ticket");
      CHECK(lbl("ny4").find("SLOT  TAKEN") == 0, "slot line says TAKEN while a position is open");
      // MT5 draws at most 63 characters of a label: no piece may exceed it, and a long text is split, not cut
      bool fits = true;
      for(auto &kv : SIM.objs)
         if(kv.first.compare(0, 5, "NQEA_") == 0 && kv.second.s[OBJPROP_TEXT].size() > 63) { fits = false; std::printf("    too long: %s = %s\n", kv.first.c_str(), kv.second.s[OBJPROP_TEXT].c_str()); }
      CHECK(fits, "no label piece longer than 63 characters (the MT5 limit)");
      std::string longT = "LTC   risk x0.75   SL buf x1.50   spread <= 0.25 ATR   lead BTCUSD BULLISH   and a tail that makes it long";
      NqLabel("zz", 10, 10, longT, 0, 9, "Arial", ANCHOR_LEFT_UPPER);
      CHECK(obj("NQEA_P_zz").size() <= 63 && SIM.objs.count("NQEA_P_zz~1") > 0 && lbl("zz") == longT &&
            SIM.objs["NQEA_P_zz~1"].i[OBJPROP_XDISTANCE] > 10,
            "a long label is split into pieces at spaces, placed side by side, nothing lost");
      NqLabel("zz", 10, 10, "short", 0, 9, "Arial", ANCHOR_LEFT_UPPER);
      CHECK(lbl("zz") == "short" && SIM.objs.count("NQEA_P_zz~1") == 0, "a shorter text removes the stale pieces");
      ObjectsDeleteAll(0, "NQEA_P_zz");
   }
   end("A9");

   begin("A11 the verdict: HOLD / EXIT on a running position, PRICE NEAR with a chart marker, WAIT otherwise");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      size_t i = START + 1;
      int reg = 0;
      for(; i <= END; i++) { stepTo(i); reg = g_s5.regime[g_s5.n - 1]; if(reg != NQ_REG_CHOP) break; }
      CHECK(reg != NQ_REG_CHOP, "found a directional regime");
      CHECK(lbl("state").find("WAIT") == 0 || lbl("state").find("PRICE NEAR") != std::string::npos || lbl("state").find("SCALP") == 0,
            "no position: the verdict is WAIT / PRICE NEAR / SCALP");
      // a position WITH the regime -> HOLD; against it -> EXIT (bot does not close plan positions by default)
      SIM.ord.clear();
      SIM.pos.clear();
      SimPos p;
      p.ticket = 4242; p.sym = "BTCUSD"; p.type = (reg > 0) ? POSITION_TYPE_BUY : POSITION_TYPE_SELL; p.vol = 0.05; p.open = SIM.bid;
      p.sl = 0; p.tp = 0; p.time = SIM.now; p.magic = InpMagic; p.comment = "NQ-Q4242";
      SIM.pos.push_back(p);
      OnTimer();
      CHECK(lbl("state").find("HOLD") == 0 && lbl("state").find("#4242") != std::string::npos, "with the regime: HOLD #ticket");
      SIM.pos[0].type = (reg > 0) ? POSITION_TYPE_SELL : POSITION_TYPE_BUY;
      OnTimer();
      CHECK(lbl("state").find("EXIT") == 0 && lbl("state").find("REGIME FLIPPED") != std::string::npos && lbl("state").find("you decide") != std::string::npos,
            "against the regime: EXIT #ticket - regime flipped (you decide)");
      size_t before = SIM.sent.size();
      stepTo(i + 1);
      bool closed = false;
      for(size_t k = before; k < SIM.sent.size(); k++) if(SIM.sent[k].action == TRADE_ACTION_DEAL && SIM.sent[k].position == 4242) closed = true;
      CHECK(!closed, "InpPlanCloseOnFlip=false: the bot leaves the plan position to the human");
      // a waiting plan order near the price -> PRICE NEAR verdict + NEAR marker on the chart
      SIM.pos.clear();
      bool nearShown = false;
      for(size_t j = i + 2; j <= END; j++)
      {
         stepTo(j);
         NqPlan pl;
         double atr5 = g_s5.atr[g_s5.n - 1];
         for(int q = 0; q < NQ_PLAN_SLOTS; q++)
         {
            if(!NqSlotPlan(q, pl) || pl.status != NQ_PL_ACTIVE) continue;
            double ask = SIM.bid + SIM.spreadPts * SIM.point;
            double d = NqPlanIsStop(pl) ? NqDistAtrStop(pl.dir, pl.entry, SIM.bid, ask, atr5) : NqDistAtr(pl.dir, pl.entry, SIM.bid, ask, atr5);
            if(d >= 0 && d <= InpNearAtr && SIM.pos.empty())
            {
               nearShown = (lbl("state").find("PRICE NEAR") != std::string::npos) && SIM.objs.count("NQEA_A_NEAR") > 0;
               break;
            }
         }
         if(nearShown) break;
      }
      CHECK(nearShown, "a level within 0.5 ATR: verdict PRICE NEAR and a NEAR marker object on the chart");
   }
   end("A11");

   begin("A12 journal: every plan event as one JSON line in the file and one POST to SignalMesh, secret never logged, queue on failure");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      g_webUrl = "https://status.example/webhooks/brain/signal";
      g_webSecret = "s3cr3t-token";
      run(START + 1, END);
      std::string fname = "NQ_events_BTCUSD.jsonl";
      CHECK(SIM.files.count(fname) == 1, "journal file NQ_events_<symbol>.jsonl exists");
      std::vector<std::string> lines;
      {
         std::string body = SIM.files[fname];
         size_t pos = 0;
         while(pos < body.size())
         {
            size_t e = body.find('\n', pos);
            if(e == std::string::npos) e = body.size();
            if(e > pos) lines.push_back(body.substr(pos, e - pos));
            pos = e + 1;
         }
      }
      std::printf("    %zu journal lines, %zu POSTs\n", lines.size(), SIM.web.size());
      CHECK(lines.size() > 20, "events were written");
      int badJson = 0;
      std::set<std::string> events, ids;
      int armedFirst = 0, ordered = 0;
      std::map<std::string, std::vector<std::string>> perId;
      for(const std::string &l : lines)
      {
         if(l.front() != '{' || l.back() != '}') badJson++;
         for(const char *k : {"\"signal_id\":", "\"system\":\"NQ-EA\"", "\"symbol\":\"BTCUSD\"", "\"event\":", "\"status\":", "\"plan_kind\":",
                              "\"entry\":", "\"sl\":", "\"tp1\":", "\"fired_at\":", "\"ts\":", "\"account_mode\":\"demo\""})
            if(l.find(k) == std::string::npos) badJson++;
         size_t a = l.find("\"event\":\"") + 9, b = l.find('"', a);
         std::string ev = l.substr(a, b - a);
         events.insert(ev);
         size_t c = l.find("\"signal_id\":\"") + 13, d = l.find('"', c);
         std::string id = l.substr(c, d - c);
         ids.insert(id);
         perId[id].push_back(ev);
         if(l.find("s3cr3t") != std::string::npos) badJson++;   // the secret is a header, never a field
      }
      CHECK(badJson == 0, "every line is a JSON object with the platform fields; the secret is never in a payload");
      for(auto &kv : perId)
      {
         if(kv.second.front() == "armed") armedFirst++;
         // a plan's life: armed, then placed/rejected/near..., then at most one terminal event
         int terminal = 0;
         for(const std::string &e : kv.second)
            if(e == "tp1" || e == "sl" || e == "false_break" || e == "expired" || e == "cancelled" || e == "replaced") terminal++;
         if(terminal <= 1) ordered++;
      }
      CHECK(armedFirst == (int)perId.size(), "the first event of every plan is 'armed'");
      CHECK(ordered == (int)perId.size(), "at most one terminal event per plan");
      CHECK(events.count("placed") && (events.count("filled") || events.count("tp1") || events.count("sl")) &&
            (events.count("expired") || events.count("replaced") || events.count("cancelled")),
            "placed, filled/closed and cancelled events all occur");
      // status mapping onto the platform vocabulary, never 'approved' (that word fans out Telegram alerts)
      int approved = 0, badMap = 0;
      for(const std::string &l : lines)
      {
         if(l.find("\"status\":\"approved\"") != std::string::npos) approved++;
         bool tp = l.find("\"event\":\"tp1\"") != std::string::npos;
         bool sl = l.find("\"event\":\"sl\"") != std::string::npos;
         if(tp && (l.find("\"status\":\"closed\"") == std::string::npos || l.find("\"outcome\":\"win\"") == std::string::npos)) badMap++;
         if(sl && (l.find("\"status\":\"closed\"") == std::string::npos || l.find("\"outcome\":\"loss\"") == std::string::npos)) badMap++;
         if(l.find("\"event\":\"armed\"") != std::string::npos && l.find("\"status\":\"pending\"") == std::string::npos) badMap++;
      }
      CHECK(approved == 0 && badMap == 0, "armed=pending, tp1=closed/win, sl=closed/loss, never approved");
      // POSTs: one per line, right URL, secret in the header, never in the Experts log
      CHECK(SIM.web.size() == lines.size(), "one POST per journal line");
      bool hdr = !SIM.web.empty();
      for(auto &w : SIM.web)
         if(w.url != "https://status.example/webhooks/brain/signal" || w.method != "POST" ||
            w.headers.find("X-Brain-Secret: s3cr3t-token") == std::string::npos ||
            w.headers.find("Content-Type: application/json") == std::string::npos || w.body != w.body) hdr = false;
      CHECK(hdr, "POST to the configured URL with X-Brain-Secret and JSON content type");
      bool leaked = false;
      for(const std::string &l : SIM.log) if(l.find("s3cr3t") != std::string::npos) leaked = true;
      CHECK(!leaked, "the secret never appears in the log");
      // the platform down: events are queued in order and drained once it answers
      size_t webBefore = SIM.web.size(), linesBefore = lines.size();
      SIM.webCode = -1;
      run(END - 1439, END - 1300);   // re-run a slice of bars: new events appear (statuses differ from the recorded ones)
      size_t fileLines = 0;
      for(char ch : SIM.files[fname]) if(ch == '\n') fileLines++;
      int queued = g_webN;
      std::printf("    queued while down: %d (file grew by %zu)\n", queued, fileLines - linesBefore);
      CHECK(fileLines > linesBefore, "the file keeps every event while the platform is down");
      CHECK(queued > 0 && queued == (int)(fileLines - linesBefore), "every undelivered event is queued");
      SIM.webCode = 200;
      for(int k = 0; k < 400 && g_webN > 0; k++) { SIM.now += 5; OnTimer(); }
      CHECK(g_webN == 0 && SIM.web.size() >= webBefore + (fileLines - linesBefore), "the queue drains in order once the platform answers");
      (void)webBefore;
   }
   end("A12");

   begin("A13 telemetry: an ANALYSIS ONLY snapshot to its own URL on every closed M1 candle and every N seconds, demo only, secret in the header, never a plan event");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.gmtOffsetSec = 3 * 3600;
      startAt(START);
      relax();
      g_webUrl = "";                                   // journal off: every POST below is telemetry
      g_telUrl = "https://status.example/webhooks/metal/telemetry";
      g_telSec = 60;
      g_telDemoOnly = true;
      g_webSecret = "s3cr3t-token";
      size_t before = SIM.web.size();
      run(START + 1, START + 30);
      size_t posts = SIM.web.size() - before;
      std::printf("    %zu telemetry POSTs over 30 closed M1 bars\n", posts);
      CHECK(posts == 30, "exactly one snapshot per closed M1 candle");
      bool routed = posts > 0;
      std::string last;
      for(size_t i = before; i < SIM.web.size(); i++)
      {
         const auto &w = SIM.web[i];
         if(w.url != g_telUrl || w.method != "POST" || w.headers.find("X-Brain-Secret: s3cr3t-token") == std::string::npos ||
            w.headers.find("Content-Type: application/json") == std::string::npos)
            routed = false;
         last = w.body;
      }
      CHECK(routed, "every snapshot goes to the telemetry URL, JSON, secret in the header");
      CHECK(last.rfind("{\"system\":\"NQ-EA\",\"kind\":\"telemetry\",\"mode\":\"ANALYSIS_ONLY\"", 0) == 0, "the snapshot names itself ANALYSIS_ONLY before anything else");
      int braces = 0, brackets = 0;
      bool inStr = false;
      for(size_t i = 0; i < last.size(); i++)
      {
         char ch = last[i];
         if(inStr) { if(ch == '\\') i++; else if(ch == '"') inStr = false; continue; }
         if(ch == '"') inStr = true;
         else if(ch == '{') braces++;
         else if(ch == '}') braces--;
         else if(ch == '[') brackets++;
         else if(ch == ']') brackets--;
      }
      CHECK(braces == 0 && brackets == 0 && !inStr && last.back() == '}', "the snapshot is balanced JSON");
      for(const char *k : {"\"label\":\"ANALYSIS ONLY - DEMO - NOT A TRADE SIGNAL\"", "\"source\":\"NRTR_QML_CryptoScalper\"", "\"ea_version\":\"1.3.3\"", "\"prof_risk\":1.00", "\"prof_spread_atr\":0.15", "\"lead_symbol\":\"\"", "\"htf\":{", "\"witnesses\":{", "\"macro\":{", "\"news\":{\"state\":\"CLEAR\"", "\"session\":{", "\"portfolio\":{", "\"smart_exit\":{",
                           "\"symbol\":\"BTCUSD\"", "\"coin\":\"BTC\"", "\"account_mode\":\"demo\"", "\"ts_server\":", "\"ts_gmt\":",
                           "\"server_offset_sec\":10800", "\"heartbeat_sec\":60", "\"clock\":\"AUTO\"", "\"clock_offset_min\":180", "\"ny_dst\":true", "\"ny_open_min\":990", "\"london_open_min\":600", "\"asia_open_min\":60", "\"rollover_min\":0", "\"fresh\":true", "\"candles\":{\"state\":\"CLOSED FRESH\"",
                           "\"m1_closed_server\":", "\"m1_age_sec\":", "\"atr5\":", "\"m15\":{\"context\":\"", "\"nrtr_level\":",
                           "\"m5\":{\"regime\":\"", "\"structure\":\"", "\"structure_state\":\"", "\"lookback\":3", "\"reasons\":[",
                           "\"m1\":{\"nrtr_dir\":\"", "\"trigger\":\"", "\"forecast_next\":\"", "\"forecast_resolved\":",
                           "\"observed\":{\"label\":\"OBSERVED EA STATE - not a SignalMesh recommendation\"", "\"verdict\":\"", "\"gate\":[",
                           "\"scalp_row\":{\"side\":\"", "\"radar\":{\"up\":{\"state\":\"", "\"ny\":{\"high_side\":\"", "\"plans\":[",
                           "\"account\":{\"balance\":", "\"record\":{\"scalp\":{\"done\":", "\"evidence\":\""})
         CHECK(last.find(k) != std::string::npos, k);
      CHECK(last.find("\"event\":") == std::string::npos && last.find("\"status\":\"pending\"") == std::string::npos,
            "a snapshot is not a plan event: no event key, no platform status vocabulary at the top level");
      // the ages are measured on the EA's own clock: the M1 bar closed at most a few seconds before the snapshot
      {
         size_t a = last.find("\"m1_age_sec\":");
         long age = (a == std::string::npos) ? -1 : std::atol(last.c_str() + a + 13);
         CHECK(age >= 0 && age < 60, "m1_age_sec is the closed bar's age on the server clock");
      }
      // timer cadence without a new bar: one snapshot per 60 s, not one per tick
      size_t b2 = SIM.web.size();
      for(int k = 0; k < 6; k++) { SIM.now += 10; OnTimer(); }
      CHECK(SIM.web.size() - b2 == 1, "without a new candle the heartbeat is one snapshot per 60 s");
      bool leaked = false;
      for(const std::string &l : SIM.log) if(l.find("s3cr3t") != std::string::npos) leaked = true;
      CHECK(!leaked, "the secret never appears in the log");

      // a REAL account is never the witness while demo-only is on
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.accountMode = ACCOUNT_TRADE_MODE_REAL;
      startAt(START);
      relax();
      g_webUrl = "";
      g_telUrl = "https://status.example/webhooks/metal/telemetry";
      g_telSec = 60;
      g_telDemoOnly = true;
      size_t b3 = SIM.web.size();
      run(START + 1, START + 10);
      CHECK(SIM.web.size() == b3, "REAL account + demo-only: no telemetry leaves the terminal");
      bool said = false;
      for(const std::string &l : SIM.log) if(l.find("demo-only") != std::string::npos) said = true;
      CHECK(said, "and the Experts log says why, once");
      g_telDemoOnly = false;
      run(START + 11, START + 12);
      CHECK(SIM.web.size() > b3 && SIM.web.back().body.find("\"account_mode\":\"real\"") != std::string::npos,
            "with demo-only off the snapshot says account_mode real, so the page can flag it");
      SIM.accountMode = ACCOUNT_TRADE_MODE_DEMO;
      SIM.gmtOffsetSec = 3 * 3600;
      g_telUrl = "";
      g_telDemoOnly = true;
   }
   end("A13");

   begin("A14 volatility regime: DEAD blocks new trades, EXPANSION asks more, EXTREME blocks until a fresh M5 swing; the gate names it");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 30);
      CHECK(g_volClass != NQ_VOL_UNKNOWN && g_volRatio > 0.0 && g_volAvg > 0.0, "a class is assigned once the 24h average exists");
      CHECK(lbl("k_e0v") == "VOL REGIME" && lbl("v_e0v").find("ATR5") != std::string::npos, "the VOL REGIME row shows the ratio");
      int n5 = g_s5.n;
      double keep = g_s5.atr[(size_t)n5 - 1];
      double avg = 0.0;
      for(int i = n5 - 1 - InpVolAvgBars; i < n5 - 1; i++) avg += g_s5.atr[(size_t)i];
      avg /= InpVolAvgBars;
      g_s5.atr[(size_t)n5 - 1] = avg * 0.3; NqVolRegime();
      CHECK(g_volClass == NQ_VOL_DEAD && NqVolGateBits() == NQ_K_VOL_DEAD, "0.3x the average = DEAD, gate closed");
      g_s5.atr[(size_t)n5 - 1] = avg * 1.0; NqVolRegime();
      CHECK(g_volClass == NQ_VOL_NORMAL && NqVolGateBits() == 0, "1.0x = NORMAL, gate open");
      g_s5.atr[(size_t)n5 - 1] = avg * 1.8; NqVolRegime();
      CHECK(g_volClass == NQ_VOL_EXPANSION && NqVolGateBits() == 0, "1.8x = EXPANSION, gate open (stronger confirmation instead)");
      g_s5.atr[(size_t)n5 - 1] = avg * 3.0; NqVolRegime();
      CHECK(g_volClass == NQ_VOL_EXTREME && NqVolGateBits() == NQ_K_VOL_EXTREME && g_volWaitFresh, "3.0x = EXTREME, gate closed, waiting for fresh structure");
      g_s5.atr[(size_t)n5 - 1] = avg * 1.0; NqVolRegime();
      CHECK(g_volClass == NQ_VOL_NORMAL && NqVolGateBits() == NQ_K_VOL_EXTREME, "back to NORMAL with no fresh M5 swing yet: still closed");
      CHECK(NqGateAtX(NQ_K_VOL_EXTREME, 0).find("FRESH STRUCTURE") != std::string::npos && NqGateAtX(NQ_K_SPREAD | NQ_K_VOL_DEAD, 0) == NqGateName(NQ_K_SPREAD) &&
            NqGateAtX(NQ_K_SPREAD | NQ_K_VOL_DEAD, 1).find("DEAD") != std::string::npos && NqGateAtX(NQ_K_SPREAD | NQ_K_VOL_DEAD, 2) == "",
            "the gate names the regime after the engine's own reasons");
      g_s5.atr[(size_t)n5 - 1] = keep;
      bool cleared = false;
      int waited = 0, openWhileWaiting = 0;
      for(size_t i = START + 31; i <= START + 600 && !cleared; i++)
      {
         stepTo(i);
         if(g_volWaitFresh) { waited++; if((g_gate & NQ_K_VOL_EXTREME) == 0) openWhileWaiting++; }
         else cleared = true;
      }
      CHECK(cleared && waited > 0 && openWhileWaiting == 0, "a fresh confirmed M5 swing after the extreme reopens the gate; it stayed closed until then");
      OnDeinit(0);
   }
   end("A14");

   begin("A15 spike guard: a 15-ATR up-spike blocks pullback / radar plans in its direction; a BUY on the way back gets a flashing EXIT WARNING");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 30);
      CHECK(g_volAvg > 0.0 && g_spikeDir == 0, "a quiet synthetic market: no spike");
      int n5 = g_s5.n;
      double base = g_s5.c[(size_t)n5 - 1], avg = g_volAvg;
      double keepL = g_s5.l[(size_t)n5 - 10], keepH = g_s5.h[(size_t)n5 - 4];
      CHECK(g_spikeNorm > 2.0 * avg && g_spikeNorm < 8.0 * avg, "a normal hour spans a few ATR(M5), so the ATR alone cannot define a spike");
      g_s5.l[(size_t)n5 - 10] = base - 6.0 * avg;   // the low first ...
      g_s5.h[(size_t)n5 - 4] = base + 9.0 * avg;    // ... then the high: an up-spike of 15 ATR, the close 60% back down
      NqSpikeScan();
      CHECK(g_spikeDir == 1 && near(g_spikeAtr, 15.0, 1e-6) && g_spikeX >= InpSpikeX && near(g_spikeRetr, 0.6, 1e-6) && g_spikeWarn,
            "up-spike of 15 ATR, several normal hours in one, 60% given back: EXIT WARNING armed");
      g_s5.h[(size_t)n5 - 4] = base + 1.5 * avg;
      NqSpikeScan();
      CHECK(g_spikeDir == 0, "a 7.5 ATR hour is a trending hour, not a spike");
      g_s5.h[(size_t)n5 - 4] = base + 9.0 * avg;
      NqSpikeScan();
      NqPlan pl;
      pl.dir = 1; pl.kind = NQ_PLAN_PB;
      bool pbUp = NqSpikeBlocks(pl);
      pl.kind = NQ_PLAN_RADAR;
      bool rdUp = NqSpikeBlocks(pl);
      pl.kind = NQ_PLAN_QML;
      bool qmlUp = NqSpikeBlocks(pl);
      pl.kind = NQ_PLAN_PB; pl.dir = -1;
      bool pbDn = NqSpikeBlocks(pl);
      pl.kind = NQ_PLAN_NY; pl.dir = 1;
      bool nyUp = NqSpikeBlocks(pl);
      pl.kind = NQ_PLAN_QML; pl.dir = -1;
      bool qmlDn = NqSpikeBlocks(pl);
      CHECK(pbUp && rdUp && qmlUp && nyUp && !pbDn && !qmlDn,
            "every plan kind in the spike's direction is blocked (QML and NY trap too - the bounce of a spike is not a setup); plans against the spike are not");
      SIM.ord.clear();
      SIM.pos.clear();
      SimPos p;
      p.ticket = 4343; p.sym = "BTCUSD"; p.type = POSITION_TYPE_BUY; p.vol = 0.05; p.open = SIM.bid;
      p.sl = 0; p.tp = 0; p.time = SIM.now; p.magic = InpMagic; p.comment = "NQ-Q4343";
      SIM.pos.push_back(p);
      int keepReg = g_s5.regime[(size_t)n5 - 1];
      g_s5.regime[(size_t)n5 - 1] = NQ_REG_BULL;
      NqVerdict();
      CHECK(g_verdict.find("EXIT WARNING BUY #4343") != std::string::npos && g_verdict.find("SPIKE REVERSAL") != std::string::npos &&
            g_verdict.find("60%") != std::string::npos && g_verdict.find("you decide") != std::string::npos && g_warnOn,
            "a BUY with the regime still bullish: EXIT WARNING #ticket - spike reversal, 60% back, you decide");
      NqDrawWarn();
      CHECK(SIM.objs.count("NQEA_A_WARN") > 0 && obj("NQEA_A_WARN").find("EXIT WARNING") != std::string::npos, "the warning is drawn on the chart");
      SIM.pos[0].type = POSITION_TYPE_SELL;
      NqVerdict();
      CHECK(g_verdict.find("HOLD SELL #4343") != std::string::npos || g_verdict.find("EXIT SELL #4343") != std::string::npos,
            "a SELL is not in the spike direction: no warning");
      CHECK(!g_warnOn, "no warning flag for the SELL");
      SIM.pos[0].type = POSITION_TYPE_BUY;
      g_s5.regime[(size_t)n5 - 1] = NQ_REG_BEAR;
      NqVerdict();
      CHECK(g_verdict.find("EXIT BUY #4343") != std::string::npos && g_verdict.find("REGIME FLIPPED") != std::string::npos && !g_warnOn,
            "the regime flip outranks the warning: plain EXIT");
      NqDrawWarn();
      CHECK(SIM.objs.count("NQEA_A_WARN") == 0, "the chart warning is removed with the flag");
      g_s5.regime[(size_t)n5 - 1] = keepReg;
      g_s5.l[(size_t)n5 - 10] = keepL;
      g_s5.h[(size_t)n5 - 4] = keepH;
      NqSpikeScan();
      CHECK(g_spikeDir == 0 && !g_spikeWarn, "the spike gone: nothing armed");
      SIM.pos.clear();
      OnDeinit(0);
   }
   end("A15");

   begin("A10 LTC spec (3 digits, tick value 5): SL/TP on the grid, lots from the real tick value; rejected order is logged, not retried");
   {
      Market ltc = makeMarket(5, 112.9, 0.001, 0.05, (int)DAYS);
      load(ltc, "LTCUSD", "LTC", 3, 0.001, 5.0);
      startAt(START);
      relax();
      run(START + 1, END);
      int market = 0, bad = 0;
      for(const MqlTradeRequest &r : SIM.sent)
      {
         if(r.action != TRADE_ACTION_DEAL || r.position != 0) continue;
         market++;
         if(std::fabs(r.sl * 1000.0 - std::round(r.sl * 1000.0)) > 1e-6) bad++;
         if(std::fabs(r.tp * 1000.0 - std::round(r.tp * 1000.0)) > 1e-6) bad++;
         double loss = NqLossAt(r.volume, std::fabs(r.price - r.sl), 0.001, 5.0);
         if(loss > 0.5 / 100.0 * (SIM.balance + 500.0) + 1e-6) bad++;
      }
      std::printf("    ltc: %d scalps\n", market);
      CHECK(market > 0 && bad == 0, "ltc orders on the 0.001 grid, sized from tick value 5");

      load(ltc, "LTCUSD", "LTC", 3, 0.001, 5.0);
      SIM.rejectAll = true;
      startAt(START);
      relax();
      run(START + 1, END);
      int rejects = 0;
      for(const std::string &l : SIM.log) if(l.find("REJECTED") != std::string::npos) rejects++;
      std::set<std::string> cm;
      int dupScalp = 0;
      for(const MqlTradeRequest &r : SIM.sent)
         if(r.action == TRADE_ACTION_DEAL && r.position == 0) { if(cm.count(r.comment)) dupScalp++; cm.insert(r.comment); }
      CHECK(rejects > 0 && dupScalp == 0, "rejections are logged and a rejected scalp is not re-sent for the same trigger");
   }
   end("A10");


   // ======================= v1.9: the metal's macro / news / smart-exit layer =======================
   begin("M1 news guard (USD): the MT5 calendar closes the gate around HIGH USD events, pulls resting orders, banks profit; UNKNOWN is not clear");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      CHECK(g_newsOk && !g_newsBlock && !g_newsUnknown && lbl("v_e0n").find("clear") == 0 && (g_gate & (NQ_K_NEWS | NQ_K_NEWS_UNKNOWN)) == 0,
            "a working calendar with no HIGH event: CLEAR, nothing gated");
      simAddEvent("USD", SIM.now + 20 * 60, CALENDAR_IMPORTANCE_HIGH, "Initial Jobless Claims");
      SimOrder so;
      so.ticket = 7001; so.sym = "BTCUSD"; so.type = ORDER_TYPE_BUY_LIMIT; so.vol = 0.10; so.price = SIM.bid - 2000.0; so.sl = SIM.bid - 3000.0; so.tp = SIM.bid - 1000.0;
      so.time = SIM.now; so.magic = InpMagic; so.comment = "NQ-Q1";
      SIM.ord.push_back(so);
      stepTo(START + 1);
      CHECK(g_nEv >= 1 && g_newsBlock && (g_gate & NQ_K_NEWS) != 0 && g_newsWhy.find("USD Initial Jobless Claims") == 0 && lbl("v_e0n").find("GUARD") == 0,
            "a HIGH USD event 20 min ahead: NEWS GUARD, the gate names the event");
      bool pulled = true;
      for(const SimOrder &o : SIM.ord) if(o.ticket == 7001) pulled = false;
      bool said = false;
      for(const std::string &l : SIM.log) if(l.find("NEWS GUARD: resting orders are pulled") != std::string::npos) said = true;
      CHECK(pulled && said, "the resting order was pulled with the reason");
      SIM.cal.clear();
      simAddEvent("GBP", SIM.now + 10 * 60, CALENDAR_IMPORTANCE_HIGH, "BoE Rate Decision");
      simAddEvent("EUR", SIM.now + 10 * 60, CALENDAR_IMPORTANCE_HIGH, "ECB Press Conference");
      stepTo(START + 2);
      CHECK(!g_newsBlock, "GBP and EUR events are not the metal's business: its news is the dollar's");
      simAddEvent("USD", SIM.now + 10 * 60, CALENDAR_IMPORTANCE_HIGH, "FOMC Press Conference");
      stepTo(START + 3);
      CHECK(g_newsBlock && g_newsWhy.find("USD FOMC Press Conference") == 0 && g_newsWhy.find("TOP TIER") != std::string::npos, "a USD presser counts and is TOP TIER");
      SIM.cal.clear();
      simAddEvent("USD", SIM.now + 50 * 60, CALENDAR_IMPORTANCE_HIGH, "Factory Orders");
      stepTo(START + 4);
      CHECK(!g_newsBlock && lbl("v_e0n").find("next HIGH USD Factory Orders") != std::string::npos, "a plain HIGH event 50 min away is outside the 30-min window; the row names it next");
      SIM.cal.clear();
      simAddEvent("USD", SIM.now + 50 * 60, CALENDAR_IMPORTANCE_HIGH, "FOMC Rate Decision");
      stepTo(START + 5);
      CHECK(g_newsBlock && g_newsWhy.find("TOP TIER") != std::string::npos, "FOMC 50 min away is inside the 60-min TOP TIER window");
      SIM.cal.clear();
      simAddEvent("USD", SIM.now + 10 * 60, CALENDAR_IMPORTANCE_MODERATE, "Consumer Credit");
      stepTo(START + 6);
      CHECK(!g_newsBlock, "a MODERATE event does not gate by default");
      g_newsMediumBlocks = true;
      NqNewsState();
      CHECK(g_newsBlock, "InpNewsMediumBlocks: it does");
      g_newsMediumBlocks = false;
      SIM.cal.clear();
      simAddEvent("USD", SIM.now - 40 * 60, CALENDAR_IMPORTANCE_HIGH, "Factory Orders");
      stepTo(START + 7);
      CHECK(!g_newsBlock, "40 min after a HIGH release: the window (30 min after) has closed");
      SIM.cal.clear();
      simAddEvent("USD", SIM.now - 20 * 60, CALENDAR_IMPORTANCE_HIGH, "Factory Orders");
      stepTo(START + 8);
      CHECK(g_newsBlock && g_newsWhy.find("ago") != std::string::npos, "20 min after: still inside");
      // the calendar's own reading of a release votes for its currency for InpNewsVoteHours
      SIM.cal.clear();
      simAddEvent("USD", SIM.now - 3600, CALENDAR_IMPORTANCE_HIGH, "Nonfarm Payrolls", CALENDAR_IMPACT_POSITIVE, true);
      stepTo(START + 9);
      std::string w;
      CHECK(NqNewsVote(1, w) == -1 && NqNewsVote(-1, w) == 1 && lbl("v_e0n").find("released 4h: USD Nonfarm Payrolls POSITIVE") != std::string::npos,
            "USD POSITIVE 1 h ago = dollar up = metal down: -1 for a BUY, +1 for a SELL; the row shows it");
      simAddEvent("USD", SIM.now - 2 * 3600, CALENDAR_IMPORTANCE_HIGH, "Unemployment Rate", CALENDAR_IMPACT_NEGATIVE, true);
      stepTo(START + 10);
      w = "";
      CHECK(NqNewsVote(1, w) == 0 && w.find("POSITIVE") != std::string::npos && w.find("NEGATIVE") != std::string::npos, "a USD NEGATIVE release 2 h ago cancels it: one vote each");
      SIM.cal.clear();
      simAddEvent("USD", SIM.now - 5 * 3600, CALENDAR_IMPORTANCE_HIGH, "Old release", CALENDAR_IMPACT_POSITIVE, true);
      stepTo(START + 11);
      CHECK(NqNewsVote(1, w) == 0, "a release older than InpNewsVoteHours votes nothing");
      // banking a position in profit when a window opens
      SIM.cal.clear();
      SIM.pos.clear();
      {
         const MqlRates &nb = SIM.m1[START + 12];
         SimPos p;
         p.ticket = 7101; p.sym = "BTCUSD"; p.type = POSITION_TYPE_BUY; p.vol = 0.10; p.open = nb.close - 50.0; p.sl = p.open - 100.0; p.tp = p.open + 300.0;
         p.time = SIM.now - 600; p.magic = InpMagic; p.comment = "NQ-P7101";
         SIM.pos.push_back(p);
         SimPos l = p;
         l.ticket = 7102; l.type = POSITION_TYPE_SELL; l.open = nb.close - 50.0; l.sl = l.open + 100.0; l.tp = l.open - 300.0; l.comment = "NQ-P7102";
         SIM.pos.push_back(l);
      }
      simAddEvent("USD", SIM.now + 10 * 60, CALENDAR_IMPORTANCE_HIGH, "FOMC Statement");
      stepTo(START + 12);
      bool bankedA = true, keptB = false;
      for(const SimPos &p : SIM.pos) { if(p.ticket == 7101) bankedA = false; if(p.ticket == 7102) keptB = true; }
      bool reason = false;
      for(const std::string &l : SIM.log) if(l.find("NEWS: banking +0.50R before USD FOMC Statement") != std::string::npos) reason = true;
      CHECK(bankedA && keptB && reason, "the window opens: the +0.5R BUY is banked with the reason, the losing SELL keeps its SL");
      SIM.pos.clear();
      SIM.cal.clear();
      // the calendar is re-read on the timer, not only on a new candle: an event added between candles is known within a minute
      simAddEvent("USD", SIM.now + 10 * 60, CALENDAR_IMPORTANCE_HIGH, "Fed Chair Speaks");
      g_newsReadT = SIM.now - 61;   // the last read is a minute old
      SIM.now += 30;                // 30 s into the forming candle: no new bar
      OnTimer();
      CHECK(g_newsBlock && g_newsWhy.find("USD Fed Chair Speaks") == 0 && g_seen1 == SIM.m1[START + 12].time,
            "no new candle, the last read a minute old: the timer re-read found the event and closed the gate");
      SIM.now -= 30;
      SIM.cal.clear();
      // the calendar call FAILS (the terminal has no calendar / an error): UNKNOWN with the error code, the gate closed, nothing placed
      SIM.calOk = false;
      stepTo(START + 13);
      CHECK(!g_newsOk && g_newsUnknown && g_newsErr == 5402 && (g_gate & NQ_K_NEWS_UNKNOWN) != 0 && lbl("v_e0n").find("UNKNOWN") == 0 &&
            lbl("v_e0n").find("error 5402") != std::string::npos && NqGateAtX(g_gate, 0).find("NEWS UNKNOWN") != std::string::npos,
            "a failed calendar call: NEWS UNKNOWN with the error code closes the gate and says so");
      {
         size_t sentB = SIM.sent.size();
         run(START + 14, START + 200);
         int opened = 0;
         for(size_t k = sentB; k < SIM.sent.size(); k++)
            if(SIM.sent[k].action == TRADE_ACTION_PENDING || (SIM.sent[k].action == TRADE_ACTION_DEAL && SIM.sent[k].position == 0)) opened++;
         CHECK(opened == 0, "186 candles with the calendar failing: no new order of any kind");
      }
      // the call succeeds but returns no values at all: UNKNOWN as well (an empty answer is not "no news")
      SIM.calOk = true;
      SIM.calFiller = false;
      stepTo(START + 201);
      CHECK(!g_newsOk && g_newsUnknown && (g_gate & NQ_K_NEWS_UNKNOWN) != 0, "an empty calendar answer is UNKNOWN too");
      SIM.calFiller = true;
      SIM.calOk = false;
      stepTo(START + 202);
      g_newsUnknownBlocks = false;
      NqNewsState();
      CHECK(g_newsUnknown && (NqMetalGateBits() & NQ_K_NEWS_UNKNOWN) == 0 && g_newsText.find("trading anyway") != std::string::npos, "InpNewsUnknownBlocks = false: trade blind, said plainly");
      g_newsUnknownBlocks = true;
      SIM.calOk = true;
      SIM.tester = true;
      stepTo(START + 14);
      CHECK(g_newsTester && !g_newsUnknown && !g_newsBlock && (g_gate & (NQ_K_NEWS | NQ_K_NEWS_UNKNOWN)) == 0 && lbl("v_e0n").find("N/A in the Strategy Tester") == 0,
            "the Strategy Tester has no calendar: N/A, not gated, not UNKNOWN");
      SIM.tester = false;
      OnDeinit(0);
   }
   end("M1");

   begin("M2 smart exit: bank on an M5 flip in profit, cut under water, lock the SL at +0.7R, bank on an M1 turn; a reversal plan whose regime never agreed is left alone");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      g_smartExit = true;
      size_t i = START + 1;
      int reg = 0;
      for(; i <= END; i++) { stepTo(i); reg = g_s5.regime[(size_t)g_s5.n - 1]; if(reg == NQ_REG_BULL) break; }
      CHECK(reg == NQ_REG_BULL, "found a bullish M5 regime");
      size_t n5 = (size_t)g_s5.n;
      int keep1 = g_s5.regime[n5 - 1], keep2 = g_s5.regime[n5 - 2];
      double risk = 1.0;
      auto plant = [&](ulong tk, int type, double open, const char *cmt) {
         SIM.pos.clear();
         SIM.ord.clear();
         SimPos p;
         p.ticket = tk; p.sym = "BTCUSD"; p.type = type; p.vol = 0.10; p.open = open;
         p.sl = (type == POSITION_TYPE_BUY) ? open - risk : open + risk; p.tp = (type == POSITION_TYPE_BUY) ? open + 3 * risk : open - 3 * risk;
         p.time = g_s5.t[n5 - 2]; p.magic = InpMagic; p.comment = cmt;
         SIM.pos.push_back(p);
      };
      auto closedWith = [&](ulong tk, const char *txt) {
         for(const SimPos &p : SIM.pos) if(p.ticket == tk) return false;
         for(const std::string &l : SIM.log) if(l.find(txt) != std::string::npos) return true;
         return false;
      };
      // a) the regime agreed (bar n-2 BULL), then flipped (bar n-1 BEAR): +0.3R is banked
      g_s5.regime[n5 - 2] = NQ_REG_BULL; g_s5.regime[n5 - 1] = NQ_REG_BEAR;
      plant(8001, POSITION_TYPE_BUY, SIM.bid - 0.3 * risk, "NQ-P8001");
      CHECK(NqRegimeAgreedSince(g_s5.t[n5 - 2], 1), "the regime agreed since the open");
      NqVerdict();
      CHECK(g_verdict.find("EXIT BUY #8001") == 0 && g_verdict.find("SMART EXIT banks it") != std::string::npos && g_verdict.find("+0.30R") != std::string::npos,
            "the verdict says the smart exit will bank +0.30R at the next M1 close");
      NqTrade();
      CHECK(closedWith(8001, "SMART EXIT: M5 regime flipped BEARISH against the position, banking +0.30R"), "banked with the reason");
      // b) under water: cut before the SL
      plant(8002, POSITION_TYPE_BUY, SIM.bid + 0.3 * risk, "NQ-P8002");
      NqTrade();
      CHECK(closedWith(8002, "SMART EXIT: M5 regime flipped BEARISH against the position at -0.30R - cut before the SL"), "cut at -0.30R with the reason");
      // c) a scalp under water on a flip: the scalp rule, not the smart cut
      plant(8003, POSITION_TYPE_BUY, SIM.bid + 0.3 * risk, "NQ-S8003");
      NqTrade();
      CHECK(closedWith(8003, "M5 regime turned BEARISH against the scalp"), "a scalp keeps its own flip rule");
      // d) the regime never agreed (a reversal plan filled against it): the flip means nothing, the plan runs
      g_s5.regime[n5 - 2] = NQ_REG_BEAR;
      plant(8004, POSITION_TYPE_BUY, SIM.bid - 0.3 * risk, "NQ-Q8004");
      int keepD1 = g_s1.dir[(size_t)g_s1.n - 1];
      g_s1.dir[(size_t)g_s1.n - 1] = 1;
      NqVerdict();
      CHECK(g_verdict.find("EXIT BUY #8004") == 0 && g_verdict.find("never agreed") != std::string::npos, "the verdict explains why the bot will not act");
      NqTrade();
      bool stillThere = false;
      for(const SimPos &p : SIM.pos) if(p.ticket == 8004) stillThere = true;
      CHECK(stillThere, "left to its SL / TP");
      // e) the lock: +0.8R with the regime intact moves the SL to entry + 0.1R, once
      g_s5.regime[n5 - 2] = NQ_REG_BULL; g_s5.regime[n5 - 1] = NQ_REG_BULL;
      plant(8005, POSITION_TYPE_BUY, SIM.bid - 0.8 * risk, "NQ-P8005");
      size_t before = SIM.sent.size();
      NqTrade();
      bool locked = false;
      double wantSl = NqRoundTick(SIM.pos.empty() ? 0.0 : SIM.pos[0].open + 0.1 * risk, 0.01, 2, -1);
      for(size_t k = before; k < SIM.sent.size(); k++)
         if(SIM.sent[k].action == TRADE_ACTION_SLTP && SIM.sent[k].position == 8005 && near(SIM.sent[k].sl, wantSl, 1e-9)) locked = true;
      CHECK(locked && !SIM.pos.empty() && near(SIM.pos[0].sl, wantSl, 1e-9), "SL moved to entry + 0.1R by a SLTP request; the position stays");
      bool logged = false;
      for(const std::string &l : SIM.log) if(l.find("SMART LOCK: +0.80R reached") != std::string::npos) logged = true;
      CHECK(logged, "logged with the reason");
      before = SIM.sent.size();
      NqTrade();
      int again = 0;
      for(size_t k = before; k < SIM.sent.size(); k++) if(SIM.sent[k].action == TRADE_ACTION_SLTP) again++;
      CHECK(again == 0, "never loosened, never repeated");
      NqVerdict();
      CHECK(g_verdict.find("HOLD BUY #8005") == 0 && g_verdict.find("SL locked") != std::string::npos, "HOLD ... SL locked");
      // f) the M1 bias turned against a +0.6R position: banked; at +0.3R not
      g_s1.dir[(size_t)g_s1.n - 1] = -1;
      plant(8006, POSITION_TYPE_BUY, SIM.bid - 0.6 * risk, "NQ-P8006");
      NqTrade();
      CHECK(closedWith(8006, "SMART EXIT: M1 bias turned BEARISH, banking +0.60R"), "M1 turn with +0.6R: banked");
      plant(8007, POSITION_TYPE_BUY, SIM.bid - 0.3 * risk, "NQ-P8007");
      NqTrade();
      stillThere = false;
      for(const SimPos &p : SIM.pos) if(p.ticket == 8007) stillThere = true;
      CHECK(stillThere, "+0.3R is under the M1 threshold: kept");
      // g) smart exit off: the hard rules only (a plan position on a flip says EXIT, you decide)
      g_smartExit = false;
      g_s5.regime[n5 - 1] = NQ_REG_BEAR;
      plant(8008, POSITION_TYPE_BUY, SIM.bid - 0.3 * risk, "NQ-P8008");
      NqTrade();
      stillThere = false;
      for(const SimPos &p : SIM.pos) if(p.ticket == 8008) stillThere = true;
      NqVerdict();
      CHECK(stillThere && g_verdict.find("you decide") != std::string::npos, "off: the plan position is left to the human");
      g_s1.dir[(size_t)g_s1.n - 1] = keepD1;
      g_s5.regime[n5 - 1] = keep1; g_s5.regime[n5 - 2] = keep2;
      SIM.pos.clear();
      OnDeinit(0);
   }
   end("M2");

   begin("M3 the Friday stop and the portfolio: orders pulled and profits banked before the weekend; positions across charts");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 5);
      SIM.pos.clear();
      SIM.ord.clear();
      SimOrder so;
      so.ticket = 9101; so.sym = "BTCUSD"; so.type = ORDER_TYPE_BUY_LIMIT; so.vol = 0.10; so.price = SIM.bid - 2000.0; so.sl = SIM.bid - 3000.0; so.tp = SIM.bid - 1000.0;
      so.time = SIM.now; so.magic = InpMagic; so.comment = "NQ-Q9101";
      SIM.ord.push_back(so);
      SimPos a;
      a.ticket = 9102; a.sym = "BTCUSD"; a.type = POSITION_TYPE_BUY; a.vol = 0.10; a.open = SIM.bid - 0.2; a.sl = a.open - 1.0; a.tp = a.open + 3.0;
      a.time = SIM.now - 600; a.magic = InpMagic; a.comment = "NQ-P9102";
      SIM.pos.push_back(a);
      SimPos l = a;
      l.ticket = 9103; l.type = POSITION_TYPE_SELL; l.open = SIM.bid - 0.2; l.sl = l.open + 1.0; l.tp = l.open - 3.0; l.comment = "NQ-P9103";
      SIM.pos.push_back(l);
      g_weekFriday = true;
      g_weekEdge = true;
      NqTrade();
      bool orderGone = true, aGone = true, lKept = false;
      for(const SimOrder &o : SIM.ord) if(o.ticket == 9101) orderGone = false;
      for(const SimPos &p : SIM.pos) { if(p.ticket == 9102) aGone = false; if(p.ticket == 9103) lKept = true; }
      bool r1 = false, r2 = false;
      for(const std::string &l2 : SIM.log)
      {
         if(l2.find("WEEKEND: resting orders are pulled before the Friday close") != std::string::npos) r1 = true;
         if(l2.find("WEEKEND: banking +0.20R before the Friday close") != std::string::npos) r2 = true;
      }
      CHECK(orderGone && aGone && lKept && r1 && r2, "Friday stop: the order is pulled, the +0.2R BUY is banked, the losing SELL keeps its SL (InpWeekendCloseLosers = false)");
      g_weekFriday = false;
      g_weekEdge = false;
      SIM.pos.clear();
      // the portfolio: this EA's positions on OTHER charts count (same magic)
      auto other = [&](ulong tk, const char *sym, int type) {
         SimPos p;
         p.ticket = tk; p.sym = sym; p.type = type; p.vol = 0.10; p.open = 60.0; p.sl = 0; p.tp = 0; p.time = SIM.now; p.magic = InpMagic; p.comment = "NQ-P1";
         SIM.pos.push_back(p);
      };
      other(9201, "LTCUSD", POSITION_TYPE_BUY);
      NqReadAccount();
      NqEvaluate();
      CHECK(g_portfolioPos == 1 && !g_portfolioFull && g_openCount == 0 && (g_gate & NQ_K_PORTFOLIO) == 0, "one position on another chart: counted, not this chart's slot, under the cap");
      other(9202, "LTCUSD", POSITION_TYPE_SELL);
      NqReadAccount();
      NqEvaluate();
      CHECK(g_portfolioPos == 2 && g_portfolioFull && (g_gate & NQ_K_PORTFOLIO) != 0 && NqGateAtX(g_gate, 0).find("PORTFOLIO FULL - 2 POSITIONS") != std::string::npos,
            "two positions across charts = the cap: PORTFOLIO FULL closes the gate");
      OnTimer();
      CHECK(lbl("v_e0h").find("portfolio 2 pos") != std::string::npos, "the WEEK / SMART row shows the portfolio");
      SIM.pos.clear();
      OnDeinit(0);
   }
   end("M3");

   begin("M4 higher timeframes: H1 / H4 context, confirmed structure, BOS / CHoCH classification, the HTF voters");
   {
      Market big = makeMarket(7, 4150.0, 0.01, 0.35, 40);
      load(big, "BTCUSD", "BTC", 2, 0.01, 0.01);
      SIM.h1 = toRates(agg(big.m1, 3600));
      SIM.h4 = toRates(agg(big.m1, 14400));
      const size_t START40 = 1440 * 39 + 17;
      startAt(START40);
      relax();
      CHECK(g_h1Ok && g_h4Ok && g_h1.n == 400 && g_h4.n >= 200 && g_h4.emaS[(size_t)g_h4.n - 1] > 0.0 && g_h1.emaS[(size_t)g_h1.n - 1] > 0.0,
            "400 H1 and 200+ H4 bars loaded: EMA200 ready on both");
      CHECK(lbl("v_e0t").find("H4 ") == 0 && lbl("v_e0t").find("|   H1 ") != std::string::npos && lbl("v_e0t").find("last ") != std::string::npos, "the H4 / H1 row");
      NqSeries s;
      NqSeriesResize(s, 3);
      ArrayResize(s.st, 3);
      NqSwingBreak b;
      b.pivIdx = 0; b.idx = 1; b.level = 1.0; b.close = 1.0;
      s.st[0] = NQ_ST_BULL; b.dir = 1;
      bool okB = (NqBreakKind(s, b) == "BOS");
      b.dir = -1;
      okB = okB && (NqBreakKind(s, b) == "CHoCH");
      s.st[0] = NQ_ST_BEAR;
      okB = okB && (NqBreakKind(s, b) == "BOS");
      b.dir = 1;
      okB = okB && (NqBreakKind(s, b) == "CHoCH");
      s.st[0] = NQ_ST_MIXED;
      okB = okB && (NqBreakKind(s, b) == "BREAK");
      CHECK(okB, "a close through a swing WITH the structure in force = BOS, AGAINST it = CHoCH, no structure = BREAK");
      size_t i4 = (size_t)g_h4.n - 1, i1 = (size_t)g_h1.n - 1;
      int c4 = g_h4.ctx[i4], c1 = g_h1.ctx[i1];
      g_h4.ctx[i4] = 1; g_h1.ctx[i1] = 1;
      int keepN = g_nSbH1;
      g_nSbH1 = 0;
      std::string w;
      CHECK(NqHtfVote(1, w) == 2 && w.find("H4 BULLISH +1") == 0 && w.find("H1 BULLISH +1") != std::string::npos && NqHtfVote(-1, w) == -2, "H4 and H1 context vote 1 each");
      g_h1.ctx[i1] = -1;
      CHECK(NqHtfVote(1, w) == 0, "H1 against H4: they cancel");
      // a fresh H1 CHoCH down votes its direction
      g_h1.ctx[i1] = 1;
      ArrayResize(g_sbH1, 1);
      g_sbH1[0].pivIdx = 0; g_sbH1[0].idx = g_h1.n - 2; g_sbH1[0].dir = -1; g_sbH1[0].level = 1.0; g_sbH1[0].close = 1.0;
      g_h1.st[(size_t)g_h1.n - 3] = NQ_ST_BULL;
      g_nSbH1 = 1;
      CHECK(NqHtfVote(1, w) == 1 && w.find("H1 CHoCH down -1") != std::string::npos, "a CHoCH down 1 bar ago: -1 for a BUY (counted beside the two contexts)");
      g_sbH1[0].idx = g_h1.n - 30;
      CHECK(NqHtfVote(1, w) == 2, "a CHoCH older than InpHtfChochBars votes nothing");
      g_nSbH1 = keepN;
      g_h4.ctx[i4] = c4; g_h1.ctx[i1] = c1;
      // no H1 / H4 at the broker: NO DATA, no vote, the EA runs on
      OnDeinit(0);
      SIM.h1.clear();
      SIM.h4.clear();
      startAt(START40);
      relax();
      CHECK(!g_h1Ok && !g_h4Ok && NqHtfVote(1, w) == 0 && lbl("v_e0t").find("H4 NO DATA") == 0 && g_ready, "no H1 / H4 served: NO DATA, no vote, everything else runs");
      OnDeinit(0);
   }
   end("M4");

   begin("M5 the week's edges and the rollover on the server clock: Friday stop, the first hour of the week, the weekend, the rollover window");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      g_clockGuards = true;
      datetime fri = T0 + 3 * 86400;   // T0 is Tuesday 2026-09-01: Friday the 4th
      datetime mon = T0 + 6 * 86400;   // Monday the 7th
      NqSessionScan(fri + 22 * 3600 + 30 * 60);
      CHECK(g_weekEdge && g_weekFriday && g_weekText.find("FRIDAY STOP") == 0 && (NqMetalGateBits() & NQ_K_WEEK_EDGE) != 0, "Friday 22:30 = 90 min before the close: FRIDAY STOP");
      NqSessionScan(fri + 19 * 3600);
      CHECK(!g_weekEdge && !g_rollover, "Friday 19:00: open");
      NqSessionScan(fri + 23 * 3600 + 50 * 60);
      CHECK(g_rollover && (NqMetalGateBits() & NQ_K_ROLLOVER) != 0, "23:50 = 10 min before the rollover: ROLLOVER bit");
      NqSessionScan(mon + 30 * 60);
      CHECK(g_weekEdge && !g_weekFriday && g_weekText.find("FIRST 60 MIN") == 0, "Monday 00:30: the first hour of the week");
      NqSessionScan(fri + 86400 + 3600);
      CHECK(g_weekEdge && g_weekText.find("WEEKEND") == 0, "Saturday 01:00: weekend");
      NqSessionScan(fri + 12 * 3600);
      CHECK(NqSessionName() == "LONDON" && !g_weekEdge, "Friday 12:00 = London, open");
      g_clockGuards = false;
      NqSessionScan(fri + 22 * 3600 + 30 * 60);
      CHECK(!g_weekEdge && !g_rollover, "guards off: nothing");
      OnDeinit(0);
   }
   end("M5");


   begin("M6 compact board, click-to-fold blocks, the SL guard: a position without a stop gets the plan's stop back or is closed");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 0.01);
      startAt(START);
      relax();
      run(START + 1, START + 300);
      // compact: an empty plan slot has no detail line, a filled one has; broker rows only as many as there are
      int withDetail = 0, withoutDetail = 0, badDetail = 0;
      for(int q = 0; q < NQ_PLAN_SLOTS; q++)
      {
         NqPlan pl;
         bool has = NqSlotPlan(q, pl);
         bool det = lbl(("bp" + std::to_string(q) + "d").c_str()) != "<missing>";
         if(has && det) withDetail++;
         else if(!has && !det) withoutDetail++;
         else badDetail++;
      }
      CHECK(badDetail == 0 && withDetail + withoutDetail == NQ_PLAN_SLOTS, "a detail line exactly for the slots that hold a plan");
      int brokerRows = 0;
      for(int i = 0; i < 6; i++) if(lbl(("bb" + std::to_string(i) + "0").c_str()) != "<missing>") brokerRows++;
      CHECK(brokerRows == std::max(1, std::min(6, (int)SIM.ord.size() + (int)SIM.pos.size())), "broker rows = the orders and positions there are, at least one line");
      // fold the desk: the engine rows go, the header stays and says unfold; unfold brings them back
      CHECK(lbl("k_e1") == "M15 CONTEXT" && lbl("h1").find("(click: fold)") != std::string::npos, "the desk is open");
      OnChartEvent(CHARTEVENT_OBJECT_CLICK, 0, 0.0, "NQEA_P_h1");
      CHECK(g_deskCollapsed && lbl("k_e1") == "<missing>" && lbl("h1").find("(click: unfold)") != std::string::npos && lbl("t2") != "<missing>",
            "click on the desk header: folded to its header, the board untouched");
      OnChartEvent(CHARTEVENT_OBJECT_CLICK, 0, 0.0, "NQEA_P_h1~1");
      CHECK(!g_deskCollapsed && lbl("k_e1") == "M15 CONTEXT", "a click on a piece of the header unfolds it");
      // fold the board: the banner and the reasons stay, the tables and the footer go
      OnChartEvent(CHARTEVENT_OBJECT_CLICK, 0, 0.0, "NQEA_P_title");
      CHECK(g_boardCollapsed && lbl("state") != "<missing>" && lbl("r1") != "<missing>" && lbl("t2") == "<missing>" && lbl("bf1") == "<missing>" &&
            lbl("f1") == "<missing>" && lbl("title").find("(click: unfold)") != std::string::npos && lbl("t1") != "<missing>",
            "click on the title: the board folds to its banner, the desk stays");
      OnTimer();
      CHECK(lbl("t2") == "<missing>" && lbl("state") != "<missing>", "a refresh keeps it folded");
      OnChartEvent(CHARTEVENT_OBJECT_CLICK, 0, 0.0, "NQEA_P_title");
      CHECK(!g_boardCollapsed && lbl("t2") != "<missing>" && lbl("bf1") != "<missing>", "a second click unfolds it");
      OnChartEvent(CHARTEVENT_OBJECT_CLICK, 0, 0.0, "NQEA_P_v_e1");
      CHECK(!g_boardCollapsed && !g_deskCollapsed, "a click elsewhere does nothing");
      // the SL guard
      int kp = -1;
      for(int k = g_nPlans - 1; k >= 0; k--) if(g_plans[(size_t)k].dir > 0 && g_plans[(size_t)k].sl > 0.0) { kp = k; break; }
      CHECK(kp >= 0, "a BUY plan exists in the history");
      if(kp >= 0)
      {
         const NqPlan &pp = g_plans[(size_t)kp];
         double keepBid = SIM.bid;
         SIM.pos.clear();
         SIM.ord.clear();
         SimPos p;
         p.ticket = 9301; p.sym = SIM.sym; p.type = POSITION_TYPE_BUY; p.vol = 0.10; p.open = pp.entry; p.sl = 0; p.tp = 0;
         p.time = SIM.now - 600; p.magic = InpMagic; p.comment = NqPlanComment(pp);
         SIM.pos.push_back(p);
         SIM.bid = pp.sl + pp.risk * 0.5;   // above the plan's stop: the stop is restored
         size_t before = SIM.sent.size();
         NqTrade();
         bool restored = false;
         for(size_t k = before; k < SIM.sent.size(); k++)
            if(SIM.sent[k].action == TRADE_ACTION_SLTP && SIM.sent[k].position == 9301 && near(SIM.sent[k].sl, pp.sl, 1e-9) && near(SIM.sent[k].tp, pp.tp1, 1e-9)) restored = true;
         bool logged = false;
         for(const std::string &l : SIM.log) if(l.find("SL MISSING: the plan's stop") != std::string::npos) logged = true;
         CHECK(restored && logged && !SIM.pos.empty() && near(SIM.pos[0].sl, pp.sl, 1e-9), "no stop at the broker: the plan's SL and TP1 are restored by one SLTP request, logged");
         SIM.pos.clear();
         p.ticket = 9302;
         SIM.pos.push_back(p);
         SIM.bid = pp.sl - pp.risk * 0.5;   // already beyond the stop: closed now
         NqTrade();
         bool gone = true;
         for(const SimPos &q2 : SIM.pos) if(q2.ticket == 9302) gone = false;
         bool said = false;
         for(const std::string &l : SIM.log) if(l.find("SL MISSING and the price is already beyond") != std::string::npos) said = true;
         CHECK(gone && said, "no stop and the price beyond it: closed with the reason");
         SIM.bid = keepBid;
      }
      SIM.pos.clear();
      OnDeinit(0);
   }
   end("M6");


   begin("C1 coin detector: BTC / ETH / LTC / ALT by name or base, dollar quote only, InpCoinClass forces");
   {
      CHECK(NqCoinOf("BTCUSD", "BTC", "USD", 0) == NQ_COIN_BTC && NqCoinOf("#BTCUSD.m", "", "USD", 0) == NQ_COIN_BTC &&
            NqCoinOf("XBTUSD", "XBT", "USD", 0) == NQ_COIN_BTC && NqCoinOf("BITCOIN", "", "", 0) == NQ_COIN_BTC &&
            NqCoinOf("btcusdt", "", "USDT", 0) == NQ_COIN_BTC, "BTC spellings");
      CHECK(NqCoinOf("ETHUSD", "ETH", "USD", 0) == NQ_COIN_ETH && NqCoinOf("ETH/USD", "", "", 0) == NQ_COIN_ETH &&
            NqCoinOf("LTCUSDT", "LTC", "USDT", 0) == NQ_COIN_LTC && NqCoinOf("LITECOIN", "", "", 0) == NQ_COIN_LTC, "ETH / LTC spellings");
      CHECK(NqCoinOf("SOLUSD", "SOL", "USD", 0) == NQ_COIN_ALT && NqCoinOf("DOGEUSDT", "", "USDT", 0) == NQ_COIN_ALT &&
            NqCoinOf("#XRPUSD.c", "", "USD", 0) == NQ_COIN_ALT && NqCoinOf("ADAUSD", "ADA", "USD", 0) == NQ_COIN_ALT, "altcoins by ticker");
      CHECK(NqCoinOf("LNKUSD", "LNK", "USD", 0) == NQ_COIN_ALT && NqCoinOf("LINKUSD", "LINK", "USD", 0) == NQ_COIN_ALT &&
            NqCoinOf("BNBUSD", "BNB", "USD", 0) == NQ_COIN_ALT && NqCoinOf("CHAINLINK", "", "", 0) == NQ_COIN_ALT &&
            NqCoinOf("Cardano", "", "USD", 0) == NQ_COIN_ALT && NqCoinOf("BinanceCoin", "", "", 0) == NQ_COIN_ALT &&
            NqCoinOf("Solana.m", "", "USD", 0) == NQ_COIN_ALT, "broker spellings: LNK, spelled-out names (Chainlink / Cardano / Binance / Solana)");
      CHECK(NqCoinOf("EURUSD", "EUR", "USD", 0) == NQ_COIN_NONE && NqCoinOf("XAUUSD", "XAU", "USD", 0) == NQ_COIN_NONE &&
            NqCoinOf("ETHEUR", "ETH", "EUR", 0) == NQ_COIN_NONE && NqCoinOf("ETHW", "", "", 0) == NQ_COIN_NONE &&
            NqCoinOf("AUDUSD", "AUD", "USD", 0) == NQ_COIN_NONE && NqCoinOf("FOOUSD", "FOO", "USD", 0) == NQ_COIN_NONE,
            "forex, metals, a non-dollar quote and an unknown coin are refused");
      CHECK(NqCoinOf("FOOUSD", "FOO", "USD", NQ_COIN_ALT) == NQ_COIN_ALT && NqCoinOf("ETHUSD", "ETH", "USD", NQ_COIN_LTC) == NQ_COIN_LTC &&
            NqCoinOf("EURUSD", "EUR", "USD", NQ_COIN_BTC) == NQ_COIN_BTC, "InpCoinClass forces the class (the user vouches)");
   }
   end("C1");

   begin("C2 specialist profile: the class only reduces risk and widens buffers; the panel shows it");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 1.0);
      startAt(START);
      run(START + 1, START + 3);
      CHECK(g_coinName == "BTC" && near(g_profRisk, 1.0) && near(g_profBuf, 1.0) && g_profRadar && near(g_profSpread, 0.15), "BTC profile");
      CHECK(near(g_riskMoney, NqRiskMoney(SIM.balance, InpRiskPct)) && near(g_P.qmlSlBufAtr, InpQmlSlBufAtr), "BTC: raw risk and buffers");
      CHECK(lbl("v_e0").find("BTC") == 0 && lbl("v_e0").find("risk x1.00") != std::string::npos && lbl("v_e0").find("spread <= 0.15 ATR") != std::string::npos,
            "COIN PROFILE row on the panel");
      OnDeinit(0);

      Market eth = makeMarket(11, 2450.0, 0.01, 1.2, (int)DAYS);
      load(eth, "ETHUSD.m", "ETH", 2, 0.01, 0.01);
      startAt(START);
      run(START + 1, START + 3);
      CHECK(g_coinName == "ETH" && near(g_profBuf, 1.25) && near(g_P.qmlSlBufAtr, InpQmlSlBufAtr * 1.25) &&
            near(g_P.pbSlBufAtr, InpPbSlBufAtr * 1.25) && near(g_profRisk, 1.0), "ETH: buffers x1.25, full risk");
      OnDeinit(0);

      Market sol = makeMarket(13, 148.0, 0.001, 0.07, (int)DAYS);
      load(sol, "SOLUSD", "SOL", 3, 0.001, 0.001);
      startAt(START);
      run(START + 1, START + 3);
      CHECK(g_coinName == "ALT" && near(g_profRisk, 0.5) && near(g_riskMoney, NqRiskMoney(SIM.balance, InpRiskPct) * 0.5), "ALT: half the risk money");
      CHECK(near(g_P.qmlSlBufAtr, InpQmlSlBufAtr * 1.5) && near(g_P.pbMinImpulseAtr, InpPbMinImpulseAtr * 1.25) && !g_profRadar,
            "ALT: buffers x1.5, impulse x1.25, radar plans off");
      NqPlan rp;
      rp.kind = NQ_PLAN_RADAR;
      rp.dir = 1;
      CHECK(!NqKindEnabled(rp), "ALT: a radar plan is not tradable");
      CHECK(lbl("v_e0").find("ALT") == 0 && lbl("v_e0").find("radar off") != std::string::npos, "panel says radar off for an altcoin");
      OnDeinit(0);
      load(btc, "BTCUSD", "BTC", 2, 0.01, 1.0);   // leave the shared market loaded for the next sections
   }
   end("C2");

   begin("C3 spread cap in ATR: a BTC spread of hundreds of points passes, one point over the cap blocks");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 1.0);
      SIM.spreadPts = 600;   // $6 on a $61,500 coin
      startAt(START);
      run(START + 1, START + 30);
      int cap = NqMaxSpreadPts();
      int k5 = g_s1.map[g_s1.n - 1];
      double atr5 = g_s5.atr[k5];
      CHECK(cap > 0 && near((double)cap, std::round(0.15 * atr5 / 0.01)), "the cap is 0.15 x ATR(M5) in points");
      CHECK(cap > 600 && (g_gate & NQ_K_SPREAD) == 0, "600 points is inside the cap: no spread block");
      SIM.spreadPts = cap + 1;
      stepTo(START + 31);
      CHECK((g_gate & NQ_K_SPREAD) != 0, "one point over the cap: SPREAD TOO WIDE");
      SIM.spreadPts = 20;
      OnDeinit(0);
   }
   end("C3");

   begin("C4 BTC-lead filter: the lead symbol is found from the symbol spelling; an alt break BTC points against is blocked");
   {
      Market eth = makeMarket(11, 2450.0, 0.01, 1.2, (int)DAYS);
      load(eth, "#ETHUSD.m", "ETH", 2, 0.01, 0.01);
      startAt(START);
      CHECK(g_macroSym == "", "no BTC symbol at the broker: no lead filter, nothing invented");
      OnDeinit(0);

      load(eth, "#ETHUSD.m", "ETH", 2, 0.01, 0.01);
      SIM.macro15 = toRates(btc.m15);
      SIM.macroSym = "#BTCUSD.m";   // the broker serves exactly this second symbol (the bond lookup must not find it)
      startAt(START);
      run(START + 1, START + 16);
      CHECK(g_macroSym == "#BTCUSD.m", "lead = this symbol's spelling with BTC in place of ETH");
      CHECK(g_macroDir != 0, "the lead's M15 NRTR direction is read");
      int saved = g_macroDir;
      g_macroDir = -1;
      CHECK(NqLeadBlocks(1, 0) && !NqLeadBlocks(-1, 0), "lead BEARISH: a weak UP break is blocked, a DOWN break is not");
      g_macroDir = 1;
      CHECK(!NqLeadBlocks(1, 0) && NqLeadBlocks(-1, 0), "lead BULLISH: a weak DOWN break is blocked, an UP break is not");
      g_macroDir = 0;
      CHECK(!NqLeadBlocks(1, 0) && !NqLeadBlocks(-1, 0), "no lead reading: nothing is blocked");
      g_macroDir = saved;
      CHECK(lbl("v_e0").find("lead #BTCUSD.m") != std::string::npos && lbl("v_e0").find("NO DATA") == std::string::npos, "panel names the lead and its reading");
      OnDeinit(0);
      SIM.macro15.clear();

      // a lead symbol typed by hand that the broker cannot serve: kept by name, shown as NO DATA, blocks nothing
      load(eth, "#ETHUSD.m", "ETH", 2, 0.01, 0.01);
      SIM.macro15 = toRates(btc.m15);
      SIM.macroSym = "#BTCUSD.m";
      startAt(START);
      run(START + 1, START + 16);
      g_macroSym = "BTC";
      NqReadWitnesses();
      OnTimer();
      CHECK(g_macroDir == 0 && lbl("v_e0").find("lead BTC (NO DATA - no lead filter)") != std::string::npos && !NqLeadBlocks(1, 0),
            "a lead the broker has no data for is shown as NO DATA on the COIN PROFILE row and blocks nothing");
      SIM.macroSym = "";
      OnDeinit(0);
      SIM.macro15.clear();

      load(btc, "BTCUSD", "BTC", 2, 0.01, 1.0);
      SIM.macro15 = toRates(btc.m15);
      SIM.macroSym = "BTCUSD";
      startAt(START);
      CHECK(g_macroSym == "", "BTC itself has no lead");
      OnDeinit(0);
      SIM.macro15.clear();
   }
   end("C4");

   begin("C5 journal: every event carries engine NQ-CRYPTO and the coin; the platform keys are unchanged");
   {
      load(btc, "BTCUSD", "BTC", 2, 0.01, 1.0);
      startAt(START);
      run(START + 1, END);
      auto it = SIM.files.find("NQ_events_BTCUSD.jsonl");
      bool have = it != SIM.files.end() && !it->second.empty();
      int missing = 0, lines = 0;
      if(have)
      {
         std::string s = it->second;
         size_t p = 0;
         while(p < s.size())
         {
            size_t e = s.find('\n', p);
            if(e == std::string::npos) e = s.size();
            std::string l = s.substr(p, e - p);
            if(!l.empty())
            {
               lines++;
               for(const char *k : {"\"engine\":\"NQ-CRYPTO\"", "\"coin\":\"BTC\"", "\"system\":\"NQ-EA\"", "\"symbol\":\"BTCUSD\"", "\"signal_id\":\"NQ:BTCUSD:"})
                  if(l.find(k) == std::string::npos) missing++;
            }
            p = e + 1;
         }
      }
      CHECK(have && lines > 0 && missing == 0, "engine + coin on every journal line, platform keys intact");
      OnDeinit(0);
   }
   end("C5");

   begin("C6 lead override: the coin's own A+ structure (score, M15 context, M5 regime) beats a lead against; a weak one does not");
   {
      Market eth = makeMarket(11, 2450.0, 0.01, 1.2, (int)DAYS);
      load(eth, "#ETHUSD.m", "ETH", 2, 0.01, 0.01);
      SIM.macro15 = toRates(btc.m15);
      SIM.macroSym = "#BTCUSD.m";
      startAt(START);
      run(START + 1, START + 16);
      size_t i15 = (size_t)g_s15.n - 1, i5 = (size_t)g_s5.n - 1;
      int c15 = g_s15.ctx[i15], r5 = g_s5.regime[i5], md = g_macroDir;
      g_macroDir = -1; g_s15.ctx[i15] = 1; g_s5.regime[i5] = NQ_REG_BULL;
      CHECK(NqLeadBlocks(1, 8) && !NqLeadBlocks(1, 9) && !NqLeadBlocks(1, 10), "lead BEARISH: score 8 blocked, 9+ with M15 and M5 agreeing allowed");
      g_s15.ctx[i15] = -1;
      CHECK(NqLeadBlocks(1, 10), "own M15 context against the trade: no override however high the score");
      g_s15.ctx[i15] = 1; g_s5.regime[i5] = NQ_REG_CHOP;
      CHECK(NqLeadBlocks(1, 10), "own M5 regime not on side: no override");
      g_s5.regime[i5] = NQ_REG_BULL; g_macroDir = 1;
      CHECK(!NqLeadBlocks(1, 0), "lead agrees: nothing to override");
      g_macroDir = md; g_s15.ctx[i15] = c15; g_s5.regime[i5] = r5;
      OnDeinit(0);
      SIM.macro15.clear();
   }
   end("C6");
   std::printf("\nCRYPTO EA TESTS: %d checks passed, %d failed\n", g_pass, g_fail);
   return g_fail == 0 ? 0 : 1;
}
